### ISSUE TITLE
TypeScript issue when import

### ISSUE THREAD

**Issue by shian15810** [elbywan/wretch#10]
When I import wretch according to the [test](https://github.com/elbywan/wretch/blob/master/test/wretch.spec.ts) file and polyfill it as the following,

```ts
import * as formData from 'form-data';
import { URLSearchParams } from 'url';
import nodeFetch from 'node-fetch';
import wretch from 'wretch';

wretch().polyfills({
  fetch: nodeFetch,
  FormData: formData,
  URLSearchParams,
});
```

it complain that wretch.default is not a function when build with tsc.

`wretch.default().polyfills({`
`TypeError: wretch.default is not a function`

And when i change it to the syntax below,

```ts
import * as wretch from 'wretch';
```

it works, but the linter is complaining...

`[ts] Cannot invoke an expression whose type lacks a call signature.`

So what I do now is

```ts
import * as wretch from 'wretch';
import { Wretcher } from 'wretch/dist/wretcher';

((wretch as any)() as Wretcher).polyfills({
  fetch: nodeFetch,
  FormData: formData,
  URLSearchParams,
});
```

so that the type definition and `tsc build` keep working again.

Is there anything wrong with my syntax? Or is there any compiler option that is causing this?

**Comment by elbywan** [comment]
Hi @shian15810,

I think that it is related to this issue : https://github.com/Microsoft/TypeScript/issues/2719

As a workaround, I added a `default` field in the exported function which should make it compatible with the typescript commonjs transpilation and solve your issue hopefully !

I committed on the dev branch, could you check it out by running `npm install https://github.com/elbywan/wretch#dev` and tell me if everything is okay ?

Thanks !

**Comment by shian15810** [comment]
Oh yes! No more complaining from tsc in my project anymore.
Anyway, when will dev be merged into master and released to npm?

Also, thanks for your hard work on wretch!
This package has been saving me tons of time dealing with fetch.

**Comment by elbywan** [comment]
>Also, thanks for your hard work on wretch!
This package has been saving me tons of time dealing with fetch.

Many thanks for these kind words !! 😄 

>Anyway, when will dev be merged into master and released to npm?

ASAP, meaning today or tomorrow at most !
