### ISSUE TITLE
Replaying original request on token expire - wiring things up properly

### ISSUE THREAD

**Issue by mkgn** [elbywan/wretch#108]
I have a problem with getting the replay() work properly. I have gone through following links:

	• https://github.com/elbywan/wretch/issues/51
	• https://github.com/elbywan/wretch/issues/35
	• https://github.com/elbywan/wretch/issues/15
	
It seems like I am messing up with the order of execution, but couldn't figure out where.

In general the current behavior is that on 401, it gets a new token and stores it, then replay() the original request. Server now returns data but I can't capture that data. Next time if I click the link, data will be there.

So the problem here is at the replay part and getting the result after the replay. Below is my code (Btw I am using this with Vue ):

	1) I keep a prepared global fetcher Instance which will be returned to other parts of the code

    fetcher: function (forApi, retryCallback) {
            if (!this.fetcherInstance) {
                this.fetcherInstance = window.wretch()
                    .url((forApi) ? `${window.location.origin}/api` : window.location.origin)
                    .headers({ "Content-Type": "application/json" })
                    .auth(`Bearer ${(this.jwtToken) ? this.jwtToken.AccessToken : ""}`)
                    .catcher(401, (error, request) => {
                        // Renew credentials
                        window.wretch(window.location.origin + "/api/1/authentication/refreshtoken")
                            .query({ accessToken: this.jwtToken.AccessToken, refreshToken: this.jwtToken.RefreshToken })
                            .post().json()
                            .then(json => { //here I get the new token properly
                                Vue.Cookies.set("token", json); 
                                if (!json) { //something wrong clear the cookie and force login
                                    this.clearSessionAndRedirect();
                                }
                                this.jwtToken = json;
                                // Replay the original request with new credentials
                                return request.auth(`Bearer ${(this.jwtToken) ? this.jwtToken.AccessToken : ""}`)
                                    .replay()
                                    // Redefine authorized to prevent infinite loops in case or multiple 401 errors
                                    .unauthorized(err => {
                                        this.clearSessionAndRedirect();
                                    });
                            });
                    }).catcher(403, (error, request) => {
                        console.log("token invalid force login");
                        this.clearSessionAndRedirect();
                    });
            }
            return this.fetcherInstance;
    }

	2) In another place in my application:
                list(pageSize, page) {
                    this.fetcher(true) //calls above method and get global fether that has defalts configured.
                        .url("/1/localization/list")
                        .post({ "PageSize": pageSize })
                        .fetchError(error => {
			//handle error
                        })
                        .json()
                        .then(json => {
                            if (json) {
                                this.dataList = json.Data;
                                this.isDataAvailable = true;
                            }
                        });
                }

Now what happens is as long as token is active it all works perfectly. When token expires, it goes to server get the token, store it properly. Then the replay() part in fetcher() method gets called. Then it continues to calling code .then(json=>) part (2nd). At this point json is undefined. But if I refresh it, now data comes (because the the token is available from the earler refresh attempt). 

The way I have don above seems to be the way documented in https://github.com/elbywan/wretch#response-types (The original request is passed along the error and can be used in order to perform an additional request.)

So, the end result is user will have to click the link twice to get the data (first click token expired, second click you get new data). Ideally replay() should give me data back (because it hits the server). So there must be something wrong in the way I have wired this all up.

Do you notice any issue in how I have wired this up?

**Comment by elbywan** [comment]
Hi @mkgn,

> Do you notice any issue in how I have wired this up?

I think that the `return` keyword is missing:

```js
.catcher(401, (error, request) => {
    // Here:
    return window.wretch(window.location.origin + "/api/1/authentication/refreshtoken")
    /* … */
})
```

**Comment by mkgn** [comment]
Yes! that was the problem. Thank you so much.
