### ISSUE TITLE
Dist contains `const`

### ISSUE THREAD

**Issue by janvanhelvoort** [elbywan/wretch#11]
Hi,

When building our source with gulp and we use 'gulp-uglify' the following error occurs:
```
GulpUglifyError: unable to minify JavaScript
Caused by: SyntaxError: Unexpected token: keyword (const)
File: C:\dev\static\build\js\app.min.js
Line: 26603
```

line `26603`: `!function(t,r){"object"==typeof exports&&"undefined"!=typeof module?module.exports=r():"function"==typeof define&&define.amd?define(r):t.wretch=r()}(this,function(){"use strict";const t=Objec` ....

Thank you!

Jan

**Comment by elbywan** [comment]
Hi @janvanhelvoort, thanks for pointing this out !

This is related to a rollup-typescript issue : https://github.com/rollup/rollup-plugin-typescript/pull/86

Just fixed that in the dev branch, could you check it out by running `npm install https://github.com/elbywan/wretch#dev` and tell me if everything is okay ?

Thanks !

*PS: By the way the dist/bundle/wretcher.js file is already minified ! Did you consider using the dist/index.js as an es2015 entry point instead ?*

**Comment by janvanhelvoort** [comment]
yes, it works with the dev branch.

Do you have a link or example about es2015 entry point?

**Comment by elbywan** [comment]
Great, thanks for letting me know 👍 !

Regarding the entry point it really depends on your build system. 

If you are using webpack for instance you can tweak it by using the "module" field as explained in the [doc](https://webpack.js.org/configuration/resolve/#resolve-mainfields).

Also, rollup has a nice wiki page [about it](https://github.com/rollup/rollup/wiki/pkg.module) and the [benefits of es2015 modules](https://github.com/rollup/rollup/wiki/ES6-modules).
