### ISSUE TITLE
read headers from error object in .catcher(401, (error, request){})

### ISSUE THREAD

**Issue by mkgn** [elbywan/wretch#110]
I need to refreshToken() and replay the last request ONLY IF the original call was rejected because of an expired token. I do not want to call refresh token if user doesn't have permission to call the api.

So in my server (.Net core) I have a middleware that returns a custom header if Jwt token is expired. So the response headers that comes to client has value "Token-Expired" : "true"

On client I want to do a refreshtoken and re-call the api only if header contains [token-expired] entry. Currently I am using the catcher(401...) to refresh token.

However I don't get response.headers inside catcher error object. Ideally my catcher logic should be something like;

                      //other code
                      .catcher(401, (error, request) => {
                        //here my error.response.headers are undefined.
                        if (error.response.headers["Token-Expired"] === true){
                           //refresh token and reply last request

                        }else{
                          //redirect to no permission page
                        }

                    }).catcher(403, (error, request) => {
                        console.log("token invalid force login");
                        this.clearSessionAndRedirect();
                    });

Replaying works fine, I just need to get that condition added so the refresh token will only happen if the header contains "token-expired" entry.

**Comment by mkgn** [comment]
Ok so the issue can be handled in a different way also, which I tried but failed.

If I forget what I tried to do above, the question boils down to handling 403 (forbidden) state. So as of now I call my apis using below function;

        fetcher: function (forApi) {
            if (!this.fetcherInstance) {
                this.fetcherInstance = window.wretch()
                    .url((forApi) ? `${window.location.origin}/api` : window.location.origin)
                    .headers({ "Content-Type": "application/json" })
                    .auth(`Bearer ${(this.jwtToken) ? this.jwtToken.AccessToken : ""}`) // Authorization header
                    .catcher(401, (error, request) => {
                        if (!this.jwtToken) //if no token for some reason can't refresh logout and force login
                            this.clearSessionAndRedirect();
                        else {
                            return this.refreshToken(request); //refresh and try to replay last call
                        }

                    }).catcher(403, (error, request) => {
                        debugger;
                        this.clearSessionAndRedirect();
                    });
            }
            return this.fetcherInstance;
        }

Now the problem is, this doesn't come to:

                     .catcher(403, (error, request) => {
                        debugger;
                        this.clearSessionAndRedirect();
                    });

However I confirmed that server properly send the 403 response. After server send 403, at client end it shows below message

    Uncaught (in promise) SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data

What may be the problem?

**Comment by elbywan** [comment]
Hi @mkgn,

> //here my error.response.headers are undefined.

This is weird. `error.response.headers` should be a `Headers` instance, and definitely not `undefined` as demonstrated below:

```js
wretch("https://httpstat.us/401").catcher(401, (error, request) => {
    console.log(error.response.headers.get('content-type'))
    // prints: text/plain; charset=utf-8
}).get().text(console.log)
```

I think that the line `error.response.headers["Token-Expired"] === true` is wrong. First you should retrieve headers using `.get` and not the brackets notation. Then, a header value is a string, not a boolean.

Check [the MDN Headers page](https://developer.mozilla.org/en-US/docs/Web/API/Headers) for more details about how to manipulate headers with javascript.

> What may be the problem?

I don't know, it must come from somewhere else in your program I suppose because there is nothing in the code example that seem out of place at first glance.

I'll close the issue since your problems do not seem to be related to wretch but it is more about javascript and browsers apis in general.
