### ISSUE TITLE
Cancel a file upload

### ISSUE THREAD

**Issue by harry-dev98** [elbywan/wretch#113]
Hello folks,
I have been using wretch for almost all of my projects. Wretch is <3

I had a requirement to cancel a file being upload and I am using wretch. Is there any way to cancel file uploading? 
Also, I tried googling theres something called signals used with fetch like a abort signal.

**Comment by elbywan** [comment]
Hey @harry-dev98,

> I have been using wretch for almost all of my projects. Wretch is <3

Thanks a bunch ❤️

> I had a requirement to cancel a file being upload and I am using wretch. Is there any way to cancel file uploading?
Also, I tried googling theres something called signals used with fetch like a abort signal.

Yes, abort signals can be used with wretch quite easily. The process is documented [here](https://github.com/elbywan/wretch#abortable-requests).

**Comment by harry-dev98** [comment]
Oh yea.. i never read that Readme file till end, and thought abort is not documented .. 
Thanks alot.
