### ISSUE TITLE
Don't add empty queryString to URL

### ISSUE THREAD

**Issue by xpuu** [elbywan/wretch#114]
Hi, once again thanks for your great work. I use this lib in our [3D Printer](https://www.ysoft.com/en/products/iota-hardware-division/ysoft-be3d-edee-solutions/3d-printer) UI already for 3 years and love it. I'm used to do nasty things with her e.g.:
```javascript
// id = undefined  - all printers
// id = string     - specific printer
// id = string[]   - specific printers
function getPrinterState(id) {
     return wretcher(api).query(id && { id }).get().json(res => typeof id === string ? res[id] : res)
}
```
But, as my overly attentive colleague pointed out, when you run `.query(false)` wretcher adds '?' or '&', which might confuse the api server.

I propose to add simple check to `appendQueryParams` on line [325](https://github.com/elbywan/wretch/blob/23484fdfe4a0e50f890d49ce60b546dc2246a0c0/src/wretcher.ts#L325), something like: 

```javascript
const split = url.split("?")

if (!queryString) 
    return replace ? split[0] : url

if (replace || split.length < 2)
    return split[0] + "?" + queryString

return url + "&" + queryString
```

**Comment by elbywan** [comment]
Hey @xpuu,

> Hi, once again thanks for your great work. I use this lib in our 3D Printer UI already for 3 years and love it.

❤️ 

> But, as my overly attentive colleague pointed out, when you run .query(false) wretcher adds '?' or '&', which might confuse the api server.

Thanks for reporting the issue! I've just pushed commit 15464a8 containing the fix. I'll also make a a patch release in a few minutes 📦.
