### ISSUE TITLE
Posting FormData to .NET Core Api

### ISSUE THREAD

**Issue by emaborsa** [elbywan/wretch#116]
Actually I have the same problem as the other user who posted [this](https://github.com/elbywan/wretch/issues/102) issue.
My code:

    const formData: FormData = new FormData();
    formData.append("picture", files[0]);
    
    wretch()
      .url('myApi')
      .formData(formData)
      .post()

When I run the code, debugging on chrome the payload results empty:
![wretch](https://user-images.githubusercontent.com/9129912/142895274-4cf214a0-b27b-4b19-a11e-d0f534cd4464.PNG)

 On server side C# I receive the multipart request, but the form is empty:
![wretch2](https://user-images.githubusercontent.com/9129912/142895427-4233d614-e37e-4712-8cd8-52932821be85.PNG)

**Comment by elbywan** [comment]
Hi @emaborsa,

`.formData` is a helper that takes an key/value map and will instantiate the `FormData` object and `append` values. 
It is not meant to receive an instance of `FormData` as an argument.

```js
// Try this:

wretch()
  .url('myApi')
  .formData({
    pictures: files[0]
  })
  .post()
```

See [here](https://github.com/elbywan/wretch/issues/71#issuecomment-602170947)  for another example.
