### ISSUE TITLE
Mocking Wretch for Jest

### ISSUE THREAD

**Issue by LupulescuAlexandru** [elbywan/wretch#125]
Hello, I've been trying to mock the calls made by Wretch, but with no luck. Is there any kind of documentation for testing/mocking?

Thanks.

**Comment by elbywan** [comment]
Hey @LupulescuAlexandru,

> Hello, I've been trying to mock the calls made by Wretch, but with no luck. Is there any kind of documentation for testing/mocking?

I think that mocking `wretch` should [not be different than mocking any other module](https://jestjs.io/docs/manual-mocks#mocking-node-modules). 
You could also try to [mock fetch](https://www.leighhalliday.com/mock-fetch-jest) which is used by wretch internally.
