### ISSUE TITLE
React Native Support?

### ISSUE THREAD

**Issue by kamal-j** [elbywan/wretch#132]
This is a really cool project and I want to use it in a React Native app I'm currently working on.
Is this compatible with RNs implementation of fetch? Are there any major issues i need to be aware of?

Thanks

**Comment by elbywan** [comment]
Hey @kamal-j,

Since the react-native implementation of `fetch` is closely related the the browser standard I think that `wretch` should work seamlessly.

**Comment by kamal-j** [comment]
That's great news! Thanks for your quick response.
I'm facing a small issue 
I did a quick test in [this](https://codesandbox.io/s/condescending-cori-e627my?file=/src/App.js) react native sandbox and wretch works fine.
But when i do the same in my react native app, I am unable to chain any of the methods after the `.post()`
I'm getting a `TypeError: undefined is not a function`
Code from react native app : 
`import wretch from 'wretch'

export default async () => {

  const response = await wretch()
    .url('https://jsonplaceholder.typicode.com/posts')
    .post({
      userId: 1,
      id: 1,
      title:
        'sunt aut facere repellat provident occaecati excepturi optio reprehenderit',
      body: 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto',
    }).json()

  return response
}
`
