### ISSUE TITLE
res.body is empty with node18 fetch

### ISSUE THREAD

**Issue by marklai1998** [elbywan/wretch#137]
Hello, I'm trying to use the latest node18 fetch with wretch so I can install less polyfill
But somehow when I do

```ts
 await wretch('some-host').url('some-url').get().res()
```
The res body is empty, It use to have the response content when I use `node-fetch` polyfill
![image](https://user-images.githubusercontent.com/18364699/177607666-a7d4f674-6fd1-4b31-bcce-29070a5f2c36.png)

**Comment by elbywan** [comment]
Hey @marklai1998,

I am not sure the problem comes from `wretch`. 

I just tried with node18, worked without any issues.

```bash
❯ node --version
v18.4.0
```

```ts
import wretch from "wretch"
const res = await wretch('https://jsonplaceholder.typicode.com/todos/1').get().res()
console.log(res.body)
const json = await res.json()
console.log(json)
```

```bash
❯ node src/index.mjs
(node:96649) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
ReadableStream { locked: false, state: 'readable', supportsBYOB: false }
{ userId: 1, id: 1, title: 'delectus aut autem', completed: false }
```
