### ISSUE TITLE
Addon types are lost after passing through the handler

### ISSUE THREAD

**Issue by gwsbhqt** [elbywan/wretch#140]
version `2.0.1`

```typescript
import { formUrlAddon } from 'wretch/addons'
import wretch from 'wretch'

export const fetch = wretch()
    .addon(formUrlAddon)
    .defer(w => w)
    .resolve(r => r.json())

export const fetch2 = wretch()
    .addon(formUrlAddon)
    .defer(w => w)
    .addon(formUrlAddon)
    .resolve(r => r.json())

export const fetch3 = wretch()
    .addon(formUrlAddon)
    .defer(w => w)
    .addon(formUrlAddon)
    .resolve(r => r.json())
    .headers({})

export const fetch4 = wretch()
    .addon(formUrlAddon)
    .defer(w => w)
    .addon(formUrlAddon)
    .resolve(r => r.json())
    .addon(formUrlAddon)
    .headers({})
```

![image](https://user-images.githubusercontent.com/16471930/182576033-18d61ac6-8287-4b32-b35a-d28eef7c2906.png)

error `TS2684: The 'this' context of type 'Wretch<FormUrlAddon, unknown, undefined>' is not assignable to method's 'this' of type 'FormUrlAddon & Wretch<FormUrlAddon, unknown, undefined>'.`

https://github.com/elbywan/wretch/blob/4c4838d668adaaf716221f6d26dd9757934ddeb3/src/types.ts#L314-L318

`Self & Wretch<Self, Chain, Resolver>` -> `Wretch<Self, Chain, Resolver>`
I found that every handler removes the self type, causes the next handler to fail to get the self type.
Is my understanding wrong?

**Comment by elbywan** [comment]
Hey @gwsbhqt, thanks for reporting the issue!

> I found that every handler removes the self type, causes the next handler to fail to get the self type.
Is my understanding wrong?

On the contrary you're absolutely right, I'm pushing a fix right now and releasing `2.0.2`.

**Comment by gwsbhqt** [comment]
nice job, timely and effective support 😄

**Comment by vkozio** [comment]
Similar problem with using `.catcher(code, async (error, originalRequest)` ...
`originalRequest ` type is `Wretch<Self, Chain, Resolver>` , not  `Self & Wretch<Self, Chain, Resolver> `
