### ISSUE TITLE
retry middleware swallows errors

### ISSUE THREAD

**Issue by dxptqhtlutehvlyxcmtg** [elbywan/wretch#141]
Thanks for this incredibly useful library.

After the retry middleware eventually exceeds `maxAttempts`, the intended error helper method is never called.

```typescript
import wretch from "wretch";
import { retry } from "wretch/middlewares/retry";

console.log("Fetching...");

wretch("https://httpstat.us")
  .middlewares([retry({ maxAttempts: 2 })])
  .get("/503")
  .error(503, (e) => {
    // this is never called
    console.log("Received 503 error");
  })
  .res((response) => {
    console.log(response);
  });
```

[Sandbox of above](https://codesandbox.io/s/currying-surf-bvw795)

Instead we encounter a "Number of attempts exceeded" exception which seemingly lacks the most recent response or any details of the underlying request failure.

**Comment by elbywan** [comment]
Hey @dxptqhtlutehvlyxcmtg,

> Thanks for this incredibly useful library.

Thanks a bunch! 🙇  

> After the retry middleware eventually exceeds maxAttempts, the intended error helper method is never called.
> Instead we encounter a "Number of attempts exceeded" exception which seemingly lacks the most recent response or any details of the underlying request failure.

I agree, it can be very useful to process the latest attempt instead of throwing an error.

I just added a flag which makes this possible (when enabled).

```ts
wretch("https://httpstat.us")
    .middlewares([retry({ maxAttempts: 2, resolveWithLatestReponse: true })])
    .get("/503")
    .error(503, (e) => {
      console.log("Received 503 error");
    })
    .res((response) => {
      console.log(response);
    });

// => Received 503 error
```

**Comment by dxptqhtlutehvlyxcmtg** [comment]
This works great. Very much appreciated, thank you.
