### ISSUE TITLE
Allow to use function to get the base URL

### ISSUE THREAD

**Issue by marklai1998** [elbywan/wretch#149]
Some time I would like to get the base URL from some remote sources like remote config in FE and internal service registry in BE services. I found it relly painful in all apiClients(not only wretch) that you have to wrap it in function to make it dynamicly

```ts
const getApiClient = ()=> {
  const url = getRemoteConfig() // get from remote sources
  return wretch(url)
}

// or

// my current solution, I don't think it looks good, because it uses middleware in an unintended way, making the code hard to understand
const apiClient = wretch().middlewares([
 next => (url, opts)=>{
  const base = getRemoteConfig() // get from remote sources
   return next(`${base}${url}`,opts)
  }
])

```

I think it would be nice for the base URL param to support function, to separate it form middlewares
```ts
const apiClient = wretch(()=>getRemoteConfig()).middlewares([
  // it can focus on other things
])

```

**Comment by elbywan** [comment]
Hey @marklai1998,

This is a great use case for the [`.defer`](https://elbywan.github.io/wretch/api/interfaces/index.Wretch.html#defer) function:

```ts
const apiClient = wretch().defer((w, url) => w.url(`${getRemoteConfig()}${url}`, true))
```

**Comment by marklai1998** [comment]
Thanks a lot, I haven't thought it can use it this way

**Comment by marklai1998** [comment]
@elbywan hello, seems the `defer` is missing in the V2 doc where it used to be there in V1

**Comment by marklai1998** [comment]
also does defer support promise? I'm cannot get the Ts to work

**Comment by elbywan** [comment]
> hello, seems the defer is missing in the V2 README doc where it used to be there in V1

@marklai1998 The defer doc is located here: https://elbywan.github.io/wretch/api/interfaces/index.Wretch.html#defer

> also does defer support promise? I'm cannot get the Ts to work

I'm not sue I understand, `.defer` is not meant to return a promise at all - maybe you can check the `.resolve` method instead?  https://elbywan.github.io/wretch/api/interfaces/index.Wretch.html#resolve

**Comment by marklai1998** [comment]
> 

Sorry, I didn't put the correct code example at first, I would like to use async await to get the config.

Some background for it is that my company is using service-oriented architecture, which we need to fetch the service IP from registry, so that's why its an async call, I think if its from a general remote location(like firebase) it requires promise as well

I can now implement this with middleware since it can accept promises, I am just not sure a feature request to "defer supports promise" is a good idea

**Comment by elbywan** [comment]
> Some background for it is that my company is using service-oriented architecture, which we need to fetch the service IP from registry, so that's why its an async call, I think if its from a general remote location(like firebase) it requires promise as well

Ah I see 🙇 

> I can now implement this with middleware since it can accept promises, I am just not sure a feature request to "defer supports promise" is a good idea

Yes I think for this specific use case the middleware function is the right tool to use.
