### ISSUE TITLE
Jest package import error

### ISSUE THREAD

**Issue by 4rmr3d1** [elbywan/wretch#150]
I'm importing the addon like it mentioned in documentation
`import AbortAddon from 'wretch/addons/abort';`

But when tests running, I have an issue:

`Cannot find module 'wretch/addons/abort' from 'src/my/route/file.ts'`

How I suppose to import this lib to avoid the problems? Looks like there is some default exports problems

**Comment by elbywan** [comment]
Hey @4rmr3d1,

From the [jest documentation](https://jestjs.io/docs/ecmascript-modules):

```
Jest ships with experimental support for ECMAScript Modules (ESM).

The implementation may have bugs and lack features. For the latest status check out the [issue](https://github.com/facebook/jest/issues/9430) and the [label](https://github.com/facebook/jest/labels/ES%20Modules) on the issue tracker.

Also note that the APIs Jest uses to implement ESM support are still [considered experimental by Node](https://nodejs.org/api/vm.html#vm_class_vm_module) (as of version 18.8.0).
```

I doubt there is something wrong with `wretch` since I was able to make it work see: https://github.com/elbywan/wretch/issues/144
