### ISSUE TITLE
Can I override .json() chain block?

### ISSUE THREAD

**Issue by qwe3qwe3lott** [elbywan/wretch#153]
Hi!

I need to modify every response from backend.
So, I am trying to override .json() chain block, because middlewares for requests modifying only.
```
export const middlewareAddon: WretchAddon<unknown> = {
  test() {
    console.log('lol');
    return {
      ...this,
    };
  },
  json(jsObject, contentType) {
    console.log('lol2');
    const currentContentType = extractContentType(this._options.headers);
    return this.content(
      contentType ||
        (isLikelyJsonMime(currentContentType) && currentContentType) ||
        JSON_MIME,
    ).body(JSON.stringify(jsObject));
  },
};
```
I want not to refactor every react-query hook.
Hope to keep them looks like that:
```
return useQuery(['apps'], async () => {
  return await apiRequest
    .url('/applicationData/retrieveUserApps')
    .test() // except of this line
    .get()
    .json<ResponseDataArray<Application>>();
});
```
In addon above I placed two "console.log" and wrapped my wretch api instance into another one.

![изображение_2022-11-25_122949611](https://user-images.githubusercontent.com/56865278/203947107-92ee31a0-27dc-4dc8-ac4c-fe3983c15f0d.png)

So, in console I see that my addon was applied successfully, but there is only one message (just "lol")

tried on wretch v2.1.5 and v2.0.0

P.S. Also, it will be great if I will be able to determine processing into ".json()" block based on "_url" of instance. For example, if I need to modify responses from specific URL

**Comment by elbywan** [comment]
Hey @qwe3qwe3lott,

> So, in console I see that my addon was applied successfully, but there is only one message (just "lol")

I think you are confusing the `.json` call to pass the body to the request with the one to parse the response body.

If you put the `.json` call **before** `.get` then I think it should call your override (assuming the addon is written correctly - it should export a `wretch: {}` object like [here](https://github.com/elbywan/wretch/blob/master/src/addons/formUrl.ts#L54) for instance).

```
.test()
.json<ResponseDataArray<Application>>()
.get()
.json() // or any other way of parsing the reponse body
```

> P.S. Also, it will be great if I will be able to determine processing into ".json()" block based on "_url" of instance. For example, if I need to modify responses from specific URL

The [.defer](https://elbywan.github.io/wretch/api/interfaces/index.Wretch.html#defer) method can be helpful for this use case.

**Comment by qwe3qwe3lott** [comment]
Thanks for the answer!

@elbywan 
Am I logicaly right, that I can use [defer](https://elbywan.github.io/wretch/api/interfaces/index.Wretch.html#defer) to configure requersts based on context and use [resolve](https://elbywan.github.io/wretch/api/interfaces/index.Wretch.html#resolve) to process repsonses (from .get, .post, ect) based on contentType (.json, .blob, .text) or status (.res, .cacher, .notFound, ect)?

**Comment by elbywan** [comment]
@qwe3qwe3lott Yes, you can use `.defer` to configure the requests just before they get sent (based on any criteria), and `.resolve` to program any number of operations that will get executed after the response is retrieved.

**Comment by qwe3qwe3lott** [comment]
I finally understood)

Thanks a lot!
