### ISSUE TITLE
Download and Upload Progress Indicator/Tracking

### ISSUE THREAD

**Issue by nickchomey** [elbywan/wretch#154]
It would be very neat if wretch could incorporate an easy to use API for tracking download and upload progress, like ky and axios can do. 

Upload progress was previously not possible, but it seems this should now be possible with Chromium versions > 105. 

https://developer.chrome.com/articles/fetch-streaming-requests/#streaming-request-bodies
[fetch() upload streaming - Chrome Platform Status (chromestatus.com)](https://chromestatus.com/feature/5274139738767360)

Here's an example implementation: https://stackoverflow.com/a/52860605/19510854

**Comment by elbywan** [comment]
Hey @nickchomey,

> It would be very neat if wretch could incorporate an easy to use API for tracking download and upload progress, like ky and axios can do.

Indeed, I'll look into it 👀.

**Comment by elbywan** [comment]
@nickchomey 

I just added an addon to monitor the download progress with this commit: https://github.com/elbywan/wretch/commit/37f5acb4897976d54fea8188f085eb090c577a57

Regarding upload progress, it seems to be more complicated unfortunately.
Both `Request.body` and/or uploading the body as a stream do not seem to be widely supported yet:

- https://github.com/whatwg/fetch/issues/1438
- https://developer.mozilla.org/en-US/docs/Web/API/Request/body#browser_compatibility

So for the moment it does not seem reasonable to implement it.
