### ISSUE TITLE
Rollup failed to resolve import "wretch/middlewares"

### ISSUE THREAD

**Issue by sh-ravan** [elbywan/wretch#160]
I can't get the built-in middleware to work in my Vite project. I have `"wretch": "^2.3.0"` installed but when I try to build it, it throws an error that says, `Rollup failed to resolve import "wretch/middlewares"`. Looks like it's something to do with the bundler as it can be reproduced in both these places:

https://stackblitz.com/edit/vitejs-vite-cbj21z
https://codesandbox.io/p/sandbox/competent-elbakyan-129ojg

**Comment by elbywan** [comment]
Hey @sh-ravan,

Thanks for reporting the issue 🙏 , I managed to reproduce and this is related to the subpath exports. 

I'm looking into it and will publish a fix asap but in the meatime you can import from the nested files instead of the index:

```ts
import { retry } from "wretch/middlewares/retry"
```

**Comment by elbywan** [comment]
> Also, heckin cool library. Good riddance axios :P

Haha thanks! 😄 

I just released `wretch@2.3.1` which should solve the issue, importing from `wretch/middlewares` and `wretch/addons` should be working now 🤞.
