### ISSUE TITLE
Global catcher

### ISSUE THREAD

**Issue by viclafouch** [elbywan/wretch#162]
Hello ! 

I'm facing an issue that I don't understand and I don't find anything on the documentation.

Here my code

```js
const request = wretch(baseURL, {
  cache: 'default',
  headers
})
  .errorType('json')
  .resolve((response) => {
    return response.json()
  })
  .addon(QueryStringAddon)


export function getRestaurantPaymentModes({ cartId }) {
  return request.get(`/carts/v3/${cartId}/payment/modes`)
}
```

When I have an error, I would like to receive the JSON without doing `error.message` every time.. Is it possible to do it globally ?

Like, I want to manipulate the error before accessing it, but globally.

```js
try {
  await getRestaurantPaymentModes({ cartId: 1 })
} catch (error) {
  console.log(error) // From `error.message`
  // my json error
}
```

Someone can help plzz ?

**Comment by viclafouch** [comment]
Thanks @elbywan for your reply !

**Comment by viclafouch** [comment]
@elbywan 

Here what I'm doing, tell me if you find anything wrong.

To explain, I want to override the `WretchError` and use my own custom `Error` for all requests. Here, I create an `ApiError`, this is my custom Error, and use the `catch` of `wretch` to override the error. 

```js
export class ApiError {
  constructor(code, message, status, json = null) {
    // The message error from the backend, or a fallback
    this.message = message || 'An unknown error has occurred'
    // The code error from the backend, or a fallback
    this.code = code || 'UNKNOWN_ERROR'
    // In some rare cases, we want to access to the json error (maybe some data exist)
    this.json = json
    // The status of the error (e.g: 404, 403, 500, ...)
    this.status = status
  }
}

const request = wretch(baseUrl, {
  cache: 'default',
  headers
})
  .errorType('json')
  .resolve((response) => {
    return response.json().catch((error) => {
      const { json } = error
      throw new ApiError(
        // Don't read that, my backend is far to be perfect 😂
        json?.error?.code ?? json?.code,
        json?.error?.message ?? json?.message ?? json?.details,
        error.status,
        json
      )
    })
  })
```

Are we agree that the catch will 'catch' every errors ?

Like, doing this : 

```js
wretch("...")
  .get()
  .badRequest((err) => console.log(err.status))
  .unauthorized((err) => console.log(err.status))
  .forbidden((err) => console.log(err.status))
  .notFound((err) => console.log(err.status))
  .timeout((err) => console.log(err.status))
  .internalError((err) => console.log(err.status))
  .error(418, (err) => console.log(err.status))
  .fetchError((err) => console.log(err))
  .res();
```

is equivalent to this :

```js
wretch("...")
  .get()
  .errorType('json')
  .forbidden(() => console.log('I can still using the method, to track someting))
  .resolve((response) => {
    return response.json().catch((error) => {
      // every single error here (internalError, badRequest, etc...)
    })
  })

```

**Comment by elbywan** [comment]
@viclafouch 

> Here what I'm doing, tell me if you find anything wrong.

Hmm I don't think this will work because the `resolver` prepends (!= appends) to the response chain. The reason from what I recall is that it is impossible from the library side to precisely know when then chain ends.

For instance this code ([from the docs](https://elbywan.github.io/wretch/api/interfaces/index.Wretch.html#resolve)):

```js
const w = wretch()
  .addon(PerfsAddon())
  .resolve(resolver => resolver
    .perfs(console.log)
    .json()
  )
```

Is conceptually equivalent to:

```js
w
  .url("http://a.com")
  .get()
// <- the resolver chain is automatically injected here!
  .perfs(console.log)
  .json()
```

In your example since the resolver chain injects `.json()` which returns a Promise, calling `.notFound` or other catchers is not possible.

```js
.get(…)
// adding .forbidden() is not possible because the resolver prepends .json() before
// .json() <- Returns a Promise
.forbidden(() => console.log('I can still using the method, to track something'))
```

So one solution would be to use [`.catcher`](https://elbywan.github.io/wretch/api/interfaces/index.Wretch.html#catcher) which can be added early on in the request chain (before `.get()`):

```js
const request = wretch(baseURL)
  .errorType('json')
  .resolve((response) => {
    return response.json().catch((error) => {
      console.log("global catch")
     })
  })


await request
  .catcher(404, err => console.log("not found", err.json))
  .get(`/carts/v3/${cartId}/payment/modes`)
```

Another easy solution would be to drop `.json()` from the resolver and call it at the end of each chain.

There is an unwanted behaviour right now that gives higher priority to the global catchers compared to the specific ones but I'm going to publish a new version in a short notice that will allow the following code to work:

```js
const request = wretch(baseURL)
  .errorType("json")
  .resolve((response) => {
    return (
      response
        // .json()
        .error("Error", (error) => {
          console.log("global catch (Error class)");
        })
        .error("TypeError", (error) => {
          console.log("global type error catch (TypeError class)");
        })
    );
  });

await request
  .get(`/carts/v3/${cartId}/payment/modes`)
  .notFound((error) => {
    console.log("not found");
  })
  .json();
```

**Comment by elbywan** [comment]
Allright `2.3.2` is published and the above code should work properly now. 📦

**Comment by viclafouch** [comment]
OO nice ! Thank you !
