### ISSUE TITLE
Which ways to prevent request from sending you can advise?

### ISSUE THREAD

**Issue by qwe3qwe3lott** [elbywan/wretch#163]
Good day!

Which ways to prevent request from sending you can advise?

For example, I need to check "navigator.onLine" before sending request. If it is "false" then I should not send request and should execute some function from context.

I imagine something like this:
```js
wretchInstance
.defer((self, url, options: {ctx?: ApiRequestContext}) => {
  if (!options.ctx) {
    throw new Error('context must be provided through the wretch options');
  }

  const ctx = options.ctx;

  if (!navigator.onLine) {
    ctx.myContextFunction();
    
    // at that point I want somehow to stop execution
  }
  
  return self.headers({
    Authorization: ctx.accessToken ?? '',
  });
});
```
Hope, you can help!

**Comment by elbywan** [comment]
Hey @qwe3qwe3lott,

Hmm this seems a bit complicated to do without hijacking the Promise stack because of the return type.

```js
wretchInstance
.defer((self, url, options: {ctx?: ApiRequestContext}) => {
  if (!options.ctx) {
    throw new Error('context must be provided through the wretch options');
  }

  const ctx = options.ctx;

  if (!navigator.onLine) {
    return ctx.myContextFunction(); // what would this function return?
  }
  
  return self.headers({
    Authorization: ctx.accessToken ?? '',
  });
});

// what would be the type of result in case the browser is offline?
// what if I call '.json()' instead of res()?
const result = wretchInstance(url).get().res()
```

I guess one way of doing it would be to use a middleware, throw a custom `Error` and ignore it when caught:

```js
.resolve((r) => r.error("OfflineError", (_) => {}))
.middlewares([
  (fetch) => (url, options) => {
    if (!options.ctx) {
      throw new Error("context must be provided through the wretch options");
    }

    const ctx = options.ctx;

    if (!options.execFunction) {
      ctx.myContextFunction();

      return Promise.reject(new OfflineError());
    }
    return fetch(url, {
      ...options,
      Authorization: ctx.accessToken ?? "",
    });
  },
]);
```

**Comment by qwe3qwe3lott** [comment]
Thanks, I like this way of processing error into resolver!

Last question: can I write
```js
return Promise.reject(new OfflineError());
```
rigth into "defer"?

Or for some reasons it will be better to use middleware instead of defer for this logic?

**Comment by elbywan** [comment]
> Or for some reasons it will be better to use middleware instead of defer for such logic?

`.defer` executes synchronously and does not expect a  and the Error will be thrown right away. This means you'll have to wrap the wretch() calls into some try/catch logic.

With the middleware since the error is thrown asynchronously at request time it will be caught by `r.error("OfflineError", (_) => {})`.

**Comment by qwe3qwe3lott** [comment]
Thanks a lot!
