### ISSUE TITLE
API for handling beforeResponse?

### ISSUE THREAD

**Issue by agent-ly** [elbywan/wretch#165]
I see that the `retry` middleware actually does a "beforeResponse" kind of step and the behavior of it is unclear to me. I think it'd be cleaner if an API was introduced to handle this, maybe for addons as they already support `beforeRequest`, and insight on how they can be stacked together or the order of execution (like right now, does retry execute after throttlingCache if index is higher or lower?)

**Comment by elbywan** [comment]
Hey @agent-ly,

> I see that the retry middleware actually does a "beforeResponse" kind of step and the behavior of it is unclear to me. 

I don't think that a specific API is needed, the behaviour is actually quite simple:

```js
const myMiddleware = delay => next => async (url, opts) => {
  // Code runs here before the request is sent
  const response = await next(url, opts) // fetches
  //  Code runs here after the response is received
}
```

> how they can be stacked together or the order of execution 

The order of execution is pretty straightforwards, it matches the order of insertion.

```js
const dummyMiddleware = label => next => (url, opts) =>  console.log(label) || next(url, opts)

const w = wretch().middlewares([
    dummyMiddleware("a"),
    dummyMiddleware("b"),
    dummyMiddleware("c"),
    dummyMiddleware("d"),
])
w.get("https://jsonplaceholder.typicode.com/posts/1").res(console.log)
// => a b c d
```

**Comment by agent-ly** [comment]
@elbywan Your post clears up a lot, is there anything else I should be aware of?

**Comment by elbywan** [comment]
> Your post clears up a lot

Glad I could help 😄 

>  is there anything else I should be aware of?

Hard for me to guess, do you have any other questions on the same topic?

**Comment by agent-ly** [comment]
> Hard for me to guess, do you have any other questions on the same topic?

Hm, I guess defer could be explained further? Not quite sure what it does or its intent since it sounds like it acts like a middleware?

**Comment by elbywan** [comment]
You can check the documentation here: https://elbywan.github.io/wretch/api/interfaces/index.Wretch.html#defer
