### ISSUE TITLE
Feature request:  stale-while-revalidate

### ISSUE THREAD

**Issue by CavalcanteLeo** [elbywan/wretch#168]
Would be awesome if we could use stale while revalidate, something similar to:

https://github.com/Kong/swrv/

**Comment by elbywan** [comment]
Hey @CavalcanteLeo 👋,

I am not familiar with this library, but I think that the [Throttling Cache middleware](https://github.com/elbywan/wretch#throttling-cache-) could be fitting this use case. It supports caching requests and has several hooks to control invalidation.
