### ISSUE TITLE
How to get error json response?

### ISSUE THREAD

**Issue by SharkFourSix** [elbywan/wretch#171]
According to this https://github.com/elbywan/wretch#catchers- , I should be  able to get a response JSON object even during errors. However, the error parameter does not have a ```.json``` property. The ```.text``` property is present but having to serialize to JSON manually is very counterintuitive.
```js
wretch("...")
  .get()
  .badRequest((err) => console.log(err.json[0].Message))
  .res();
```

```javascript
type WretchError = Error & {
  status: number;
  response: WretchResponse;
  text?: string;
  json?: Object;
};
```

 Perhaps there is another way that I'm not aware of?

**Comment by elbywan** [comment]
Hey @SharkFourSix,

You can use the [`.errorType`](https://elbywan.github.io/wretch/api/interfaces/index.Wretch.html#errorType) method to specify the error body type.

**Comment by SharkFourSix** [comment]
Thanks. :+1: That worked. I was about to switch to axios because of that that little inconvenience which can build up into lots of boilerplate code :sweat_smile:

**Comment by SharkFourSix** [comment]
Bump...

So it appears that this applies to all the error "catchers"? Is there a way to only call the parsing on demand in the handlers?

Because as it appears I have to design my API to always return a JSON response, again, something which is counterintuitive :/

I'm getting a JSON conversion error because some responses are only returning standard HTTP  responses without any additional JSON data.

**Comment by elbywan** [comment]
> Because as it appears I have to design my API to always return a JSON response, again, something which is counterintuitive :/

Absolutely, I fully agree 👍.

> Can't you only parse JSON by looking at the content-type response?

No, but this is an excellent idea! I just released [`v2.5.0`](https://github.com/elbywan/wretch/releases/tag/2.5.0) which will automatically deserialize the error body if the response content-type header is set to `application/json`, which should make it unnecessary to set `.errorType` in the first place if your server sets the header properly.

The `error.text` property will still get populated in case the parsing fails.

**Comment by SharkFourSix** [comment]
Cool. That was quick too. :+1:

**Comment by Gildedter** [comment]
Having issues with `.json()`, when I return a 204 No Content, it will throw a json.parse error, which is the correct output since I'm not providing a body, I've been trying to read the status instead but I'm getting confused by the response chain, I have tried `.res()`, but calling `body.json()` inside the res chain just breaks everything
