### ISSUE TITLE
Using custom HTTPS agent object

### ISSUE THREAD

**Issue by RinkAttendant6** [elbywan/wretch#172]
Is there a way to pass in an agent object so that this can be used for client certificate authentication (or to disable certificate checks by setting `rejectUnauthorized`)?

I tried this but it did not seem to have any effect:

```typescript
  import https from 'node:https';
  import wretch from 'wretch';

  const agent = new https.Agent({ rejectUnauthorized: false });
  console.log(await wretch().options({ agent: agent }).get('https://localhost:8889/api/hello').json());
```

It works with `curl --insecure https://localhost:8889/api/hello`

See https://stackoverflow.com/questions/60061143/using-rejectunauthorized-with-node-fetch-in-node-js
And also: https://sebtrif.xyz/blog/2019-10-03-client-side-ssl-in-node-js-with-fetch/

My workaround right now is to run the script with the environment variable: `NODE_TLS_REJECT_UNAUTHORIZED=0 node ./index.mjs`
Though it is not ideal since this would disable certificate checking everywhere in the application rather than just this piece of code, and it wouldn't solve the issue for custom certificates either.

**Comment by RinkAttendant6** [comment]
Thanks for the quick response!

This is good to know. Does that mean I will need to install the node-fetch polyfill in the meantime until they add the `dispatch` option to the built-in fetch?

**Comment by elbywan** [comment]
> This is good to know. Does that mean I will need to install the node-fetch polyfill in the meantime until they add the dispatch option to the built-in fetch?

I think so, yes. Or you can pick any other fetch polyfill accepting a custom agent like [undici](https://github.com/nodejs/undici#undicifetchinput-init-promise). 

Then you should register the library of your choice using the [`.polyfills`](https://github.com/elbywan/wretch#polyfills) method to make `wretch` use it instead of the built-in fetch.

**Comment by b1rdex** [comment]
Working solution for node 21+ (with stable Fetch API):
1. install `unidici` (`npm install undici`)
2. use it's `Agent`
```ts
import { Agent } from 'undici';

wretch(API_URL)
  .options({
    dispatcher: new Agent({
      connect: {
        rejectUnauthorized: false,
      },
    }),
  })
```

This is copied from https://github.com/nodejs/undici/issues/1489#issuecomment-1543856261. There is also a solution for `ProxyAgent` too.
