### ISSUE TITLE
Node 18 implements fetch API

### ISSUE THREAD

**Issue by heath-freenome** [elbywan/wretch#174]
Update the documentation in the README appropriately now that Node 18 supports the fetch API. See this : https://dev.to/cloudx/nodejs-18-fetch-api-test-runner-module-and-more-2ckg

**Comment by heath-freenome** [comment]
@elbywan I swear I didn't see that there when I last looked. as it's a bit subtle. Might I suggest changing the `Polyfills` section to be `Polyfills (Node < 18 only)`?

**Comment by elbywan** [comment]
Just pushed [this commit](https://github.com/elbywan/wretch/commit/43556cb937f74f43a00c473e81b984ec6db7e23f), I improved the wording a bit which should make things clearer overall.

**Comment by heath-freenome** [comment]
> Just pushed [this commit](https://github.com/elbywan/wretch/commit/43556cb937f74f43a00c473e81b984ec6db7e23f), I improved the wording a bit which should make things clearer overall.

Just added a couple of suggestions to the commit.
