### ISSUE TITLE
Using types with defined api

### ISSUE THREAD

**Issue by aLemonFox** [elbywan/wretch#175]
I'm trying to use wretch to build a reusable api like in the docs:
```typescript
export const api = wretch(DEV_URL)
    .headers(headers)
    .resolve((response) => response
        .unauthorized((err) => handleUnauthorized)
        .json()
    );
```

I want to provide the same function to `.unauthorized()` for every request. But this way I can no longer easily provide the typing for the expected json return value:

```typescript
const something = api.get<ExpectedReturnValue>('/get-something');
// doesn't work
```

How can I pass along my expected return type to the res function? I think I'm missing something here which should be easily doable right?

**Comment by elbywan** [comment]
Hey @aLemonFox,

> How can I pass along my expected return type to the res function? I think I'm missing something here which should be easily doable right?

`get` will not accept a generic argument because the final type depends on how to parse the response body.

Anyway I can see a way a achieving that using typescript generics:

```typescript
type Post = { userId: string }
const api = <T>() => wretch("https://jsonplaceholder.typicode.com")
  .resolve((response) => response
    .unauthorized((err) => console.log(err))
    .json<T>()
  )

const post = await api<Post>().get('/posts/1')
console.log(post.userId)
```

But ultimately I am not sure it is way better than just casting the `unknown` typed result:

```ts
type Post = { userId: string }
const api = wretch("https://jsonplaceholder.typicode.com")
  .resolve((response) => response
    .unauthorized((err) => console.log(err))
    .json()
  )

const post = (await api.get('/posts/1')) as Post
console.log(post.userId)
```

**Comment by aLemonFox** [comment]
Hi @elbywan, thanks for the quick reply :)
I see, that would do the trick. I didn't want to cast because I thought there might have been a build in way to pass along the types, but this works too.
Thanks a lot!
