### ISSUE TITLE
Addon types are lost after passing through the catcher handler

### ISSUE THREAD

**Issue by vkozio** [elbywan/wretch#177]
Problem with defer was fixed in  https://github.com/elbywan/wretch/issues/140

But there's similar problem with using `.catcher(code, async (error, originalRequest)` ...
`originalRequest ` type is `Wretch<Self, Chain, Resolver>` , not  `Self & Wretch<Self, Chain, Resolver> `

**Comment by elbywan** [comment]
Hey @vkozio 👋 ,

Thanks for reporting the issue! I've just released `v2.5.2` which includes a fix that should hopefully provide the right types.

Feel free to reopen if I missed something.
