### ISSUE TITLE
proxy support

### ISSUE THREAD

**Issue by konsumer** [elbywan/wretch#18]
Is there a way to use a proxy?

Normally, I would setup a `HttpsProxyAgent` then pass that as `agent` to `https.get()`

**Comment by elbywan** [comment]
I guess it really depends on which fetch polyfill you are using !

If you rely on `node-fetch`, then it seems like you could use the [agent option](https://github.com/bitinn/node-fetch#options) to pass the `HttpsProxyAgent` instance.

**Comment by konsumer** [comment]
Perfect, thanks!
