### ISSUE TITLE
Doc: Typescript examples?

### ISSUE THREAD

**Issue by obouchari** [elbywan/wretch#182]
I can't find Typescript examples anywhere online! Is it possible to provide few examples? Currently I get the following error:
```
Property 'json' does not exist on type '<Result = unknown>(cb?: ((type: any) => Result | Promise<Result>) | undefined) => Promise<Awaited<Result>>'.
```

**Comment by elbywan** [comment]
Hey @obouchari,

While it is true that there are no typescript specific snippets in the readme there is pretty much nothing special to write about. Wretch should work the same way in javascript and in typescript.

Could you maybe provide more context on the error? Based on the message I can guess that typescript tells you that you are called `.json` without actually calling the function or something similarily weird.

<img width="1238" alt="Capture d’écran 2023-05-16 à 08 47 26" src="https://github.com/elbywan/wretch/assets/3428394/a4528984-c9ad-4502-83ba-0448e258619d">
<br /><br />

The right way to retrieve a property from a fetched json is:

```ts
type Todo = {
  userId: number
  id: number
  title: string
  completed: boolean
}

const todo = await wretch("https://jsonplaceholder.typicode.com/todos/1")
  .get()
  .json<Todo>()

console.log(todo)
```

**Comment by obouchari** [comment]
Thank you for the quick response! You're right, I did something weird. I was resolving to json twice?
```
const api = wretch("https://jsonplaceholder.typicode.com")
                    .addon(QueryStringAddon)
                    .auth("Bearer token")
                    .errorType("json")
                    .resolve(res => res.json)     // <= this what was causing the TS error, removing solves the issue
                    
const todo = await api.url("todos")
                                      .query({ limit: 10 })
                                      .get()
                                      .json<T>();  // TS error here
```
Also, is there a way to handle some common errors on "global" scale? something like:
```
const api = wretch('api/')
    .addon(QueryStringAddon)
    .auth(`Bearer ${process.env.NEXT_PUBLIC_GG_API_KEY}`)
    .errorType('json')
    .notFound((err) => console.log(err.status));
```

Great library BTW!

**Comment by elbywan** [comment]
> Great library BTW!

Thanks a bunch! 😄

> Thank you for the quick response! You're right, I did something weird. I was resolving to json twice?

`.resolve(res => res.json)` means that `.json` will get "appended" to the chain just after the `.get()` call.

So it is basically the equivalent of writing:

```ts
const todo = await api.url("todos")
  .query({ limit: 10 })
  .get()
  .json // <--- resolve adds this json call here
  .json<T>();  // TS error here
```

> Also, is there a way to handle some common errors on "global" scale? something like:

You can use [catchers](https://elbywan.github.io/wretch/api/interfaces/index.Wretch.html#catcher) to do that:

```ts
const w = wretch()
  .catcher(404, err => redirect("/routes/notfound", err.message))
  .catcher(500, err => flashMessage("internal.server.error"))
```

**Comment by gfsd3v** [comment]
@elbywan thanks for the great work.

Maybe this issue needs to be re-opened, I'm trying to work with the example provided but there's still a type error, it might be a regression:
![image](https://github.com/elbywan/wretch/assets/36668882/206a9302-bf56-4a31-bdb0-e018c8254749)

reproduction: https://codesandbox.io/p/sandbox/wrech-type-wrror-dpct9p?file=%2Fsrc%2Findex.ts%3A16%2C63

**Comment by elbywan** [comment]
Hey @gfsd3v,

The types seem correct to me, `.json()` return type is `unknown` by default.

You'll need to either add a generic parameter or cast the result.

```js
export const api = <T>() => wretch("https://jsonplaceholder.typicode.com")
    .auth("Bearer token")
    .errorType("json")
    .resolve((res) => res.json<Response<T>>());

const testFunc = async () => {
    // inferred as Response<number>
    const todo = await api<number>().url("todos").get();
    console.log(todo);
};
```

Or:

```js
const testFunc = async () => {
    // cast it
    const todo = await api.url("todos").get() as Response<number>;
    console.log(todo);
};
```

**Comment by gfsd3v** [comment]
Thanks for the quick help @elbywan 

Wish u all the best 🫡
