### ISSUE TITLE
Where is the full documentation?

### ISSUE THREAD

**Issue by jaclas** [elbywan/wretch#190]
What exactly is res()?
I can't realize how to use .res() and .json() on one chain?

**Comment by CanRau** [comment]
I'm just starting to use wretch but as I understand it from the readme specifically the wretch example under [motivation](https://github.com/elbywan/wretch#motivation) `.res` gives you the raw `fetch` like response, whereas `.json` is a helper to directly get `res.json()` so you can't combine them you either do

```ts
wretch("examples/example.json")
  .get()
  .json(json => {
    // Do stuff with the parsed json
  });
```

or

```ts
wretch("examples/example.json")
  .get()
  .res(async res => {
    const json = await res.json()
    // Do stuff with the parsed json
  });
```

also there's an auto-generated doc at https://elbywan.github.io/wretch

**Comment by elbywan** [comment]
Hey @jaclas,

> I'm just starting to use wretch but as I understand it from the readme specifically the wretch example under [motivation](https://github.com/elbywan/wretch#motivation) .res gives you the raw fetch like response, whereas .json is a helper to directly get res.json() so you can't combine them

Thanks @CanRau you summed it up 😉.

> Where is the full documentation?

`.res()` is a [response type](https://github.com/elbywan/wretch#response-types-) and the autogenerated documentation for this particular method is located [here](https://elbywan.github.io/wretch/api/interfaces/index.WretchResponseChain.html#res).
