### ISSUE TITLE
CatherFallback type error

### ISSUE THREAD

**Issue by dmitrybezly** [elbywan/wretch#193]
`.catcherFallback` returns an incorrect type 
![Screenshot 2023-06-28 at 15 42 57](https://github.com/elbywan/wretch/assets/90677454/726b6320-af63-40df-8912-91ec867d581f)

**Comment by elbywan** [comment]
Hey @dmitrybezly,

I have no such issue when trying to reproduce with a fresh project:

```js
// .eslintrc.cjs

/* eslint-env node */
module.exports = {
  extends: [
    "eslint:recommended",
    "plugin:@typescript-eslint/recommended",
    "plugin:@typescript-eslint/recommended-requiring-type-checking",
  ],
  parser: "@typescript-eslint/parser",
  parserOptions: {
    project: true,
    tsconfigRootDir: __dirname,
  },
  plugins: ["@typescript-eslint"],
  root: true,
  rules: {
    "@typescript-eslint/no-unsafe-call": "error",
  },
};
```

<img width="645" alt="Screenshot 2023-06-28 at 15 05 30" src="https://github.com/elbywan/wretch/assets/3428394/9966e277-3f67-4140-93bd-614bd69e7ab5">

**Comment by therealokoro** [comment]
Works for me too. I must say this came at a good time

**Comment by dmitrybezly** [comment]
It looks like it was a PhpStorm glitch :( Sorry, and thanks for your time!
