### ISSUE TITLE
Using PerfsAddon

### ISSUE THREAD

**Issue by jaclas** [elbywan/wretch#194]
How to use PerfsAddon? 
Please give me a simple example. I didn't find this in the documentation.

**Comment by elbywan** [comment]
Hey @jaclas,

> I didn't find this in the documentation.

Readme section: https://github.com/elbywan/wretch#performance-
API documentation (accessed by clicking the readme heading): https://elbywan.github.io/wretch/api/functions/addons_perfs.default.html 

Copy pasting one example from the documentation:

```js
import PerfsAddon from "wretch/addons/perfs"

// Use perfs() before the response types (text, json, ...)
wretch("...")
  .addon(PerfsAddon())
  .get()
  .perfs((timings) => {
    // Will be called when the timings are ready.
console.log(timings.startTime);
  })
  .res();
```

The `timings` argument is an instance of [PerformanceResourceTiming](https://developer.mozilla.org/en-US/docs/web/api/performanceresourcetiming).

**Comment by jaclas** [comment]
Thanks! 
And sorry, completely unintuitive for me is this form of hiding links, I can not notice them.
