### ISSUE TITLE
Upload file with file;filename (multiple parameters)

### ISSUE THREAD

**Issue by jaimesemp** [elbywan/wretch#197]
Hi, thanks a lot for this library.

I have been using it deeply, but I have some struggles with multipart/forms.

I want to change this part of the result request:

Content-Disposition: form-data; name="file"

to:

Content-Disposition: form-data; name="file"; **filename="datasheet5.pdf"**

I have tried the `FormDataAddon`, and the `.body(formData)` methods, but I have been unable to add this second parameter, in fact, I do not have any clue at all of how to achieve it. 

I am using wretch in my custom library (I want to use it on backend & frontend)

Could any give me some hints?

Thanks in advance

**Comment by jaimesemp** [comment]
Finally I did. 

I add here some minimum example (I was not able to do it using FormDataAddon):

```typescript
import * as fs from "fs"
import * as path from "path"
import FormData from 'form-data'; // this is the same library than wretch use, so i guess it should not be any problem

const duckImagePath = path.resolve(__dirname, "duck.jpg") // just place a duck.jpg in your working folder
const duckImage = fs.readFileSync(duckImagePath)

export function postFormData() {
    const formData = new FormData(); 
    formData.append('file', duckImage, {filename: 'little-duck.jpg'});
    return wretch('https://anyurlyouwant.free.beeceptor.com')
        .url('/files')
        .body(formData.getBuffer())
        .post()
        .res(console.log)
        .catch(console.error)
}

postFormData(
```

Result:

`
----------------------------834223576204015562841633
Content-Disposition: form-data; name="file"; filename="little-duck.jpg"
Content-Type: image/jpeg

����JFIF��C	
(more bytes here)
----------------------------834223576204015562841633--
`

Maybe, a little more documentation about this topic would be great

**Comment by elbywan** [comment]
Hey @jaimesemp,

> I have tried the FormDataAddon, and the .body(formData) methods, but I have been unable to add this second parameter, in fact, I do not have any clue at all of how to achieve it.

As you noticed, the `FormData` addon is just syntactic sugar around `FormData.append(…)`. Since it serializes an object (key/value) it is impossible to specify the filename as an additional argument.

> Finally I did.

Glad you nailed it in the end!

> Maybe, a little more documentation or examples about this topic would be great

I will add a little something in the addon documentation 👍.

**Comment by Gildedter** [comment]
I'm having the same issue (svelte SPA)
I have several file inputs in my form, and appending the files via `.formData()` just gives me this:
![image](https://github.com/elbywan/wretch/assets/93777256/7c85bc10-2254-475f-a7d6-0daac3d5808a)

how can I pass the actual files instead?
