### ISSUE TITLE
How should 304 responses be handled?

### ISSUE THREAD

**Issue by Rikthepixel** [elbywan/wretch#198]
Hi all, I hope this is the right platform to ask these sort of questions on.

I am writing a feature for my app with a server that can send back a 304 (Not Modified) HTTP response if it the object on the endpoint hasn't been modified past the date I give in the request. A minimal code example looks like this:

```ts
const backend =  wretch(BACKEND_URL, { credentials: "include "}).accept("application/json").content("application/json")
const exampleDate =  "Tue, 22 Feb 2022 23:22:22 GMT"

const makeQuery = (id: number, signal: AbortSignal) => {
    return backend
              .options({ signal })
              .headers({
                  "If-Modified-Since": exampleDate
              })
              .get(`/foo/${id}`)
              .json<Foo>((fooDto: MapToDto<Foo>) => FooMapper.fromFooDto(fooDto));
}
```

I assume that because the response is cached the browser automatically gives the same response body as the originally cached response, in which case I would still like to run it through the JSON parser. If any of that is incorrect, please let me know, because I am not really proficient in caching.

I am not quite sure how to handle the 304, since Wretch treats it as an error.

Thank you in advance for your help!

**Comment by alexeymarunin** [comment]
According to [HTTP Specification](https://www.rfc-editor.org/rfc/rfc9110.html#name-304-not-modified)

> A 304 response is terminated by the end of the header section; it cannot contain content or trailers.

i.e. no response body, it's just a "marker" for client.

I'm not sure, but you can try this:

```ts
const backend =  wretch(BACKEND_URL, { credentials: "include "}).accept("application/json").content("application/json")
const exampleDate =  "Tue, 22 Feb 2022 23:22:22 GMT"

const makeQuery = (id: number, signal: AbortSignal) => {
    return backend
              .options({ signal })
              .headers({
                  "If-Modified-Since": exampleDate
              })
              .get(`/foo/${id}`)
              .error(304, (err) => FooMapper.fromFooDto(err.json))
              .json<Foo>((fooDto: MapToDto<Foo>) => FooMapper.fromFooDto(fooDto));
}
```

Or you can cache previous response in app manually (in localStorage?) and load in `error()` handler.

**Comment by elbywan** [comment]
Hey @Rikthepixel,

Sorry for the late reply.

> I assume that because the response is cached the browser automatically gives the same response body as the originally cached response, in which case I would still like to run it through the JSON parser. If any of that is incorrect, please let me know, because I am not really proficient in caching.

I made some testing and I also do not think that providing the `"If-Modified-Since"` is necessary, the browser should already populate the field accordingly.

Worse, when you fill the header the browser explicitely discards the previously cached response (from https://fetch.spec.whatwg.org/):

> If [header list](https://fetch.spec.whatwg.org/#concept-request-header-list) [contains](https://fetch.spec.whatwg.org/#header-list-contains) `If-Modified-Since`, `If-None-Match`, `If-Unmodified-Since`, `If-Match`, or `If-Range`, [fetch](https://fetch.spec.whatwg.org/#concept-fetch) will set [cache mode](https://fetch.spec.whatwg.org/#concept-request-cache-mode) to "no-store" if it is "default".

I tried with the following server code:

```ts
.get("/resource", ({ request, set }) => {
    const modificationDate = new Date("Tue, 12 Sep 2023 00:00:00 GMT")
    const modifiedSince = request.headers.get("If-Modified-Since")

    set.headers = {
      "ETag": "fake-etag",
      "Last-Modified": modificationDate.toUTCString(),
      "Cache-Control": "no-cache",
    }

    if(request.headers.get("If-None-Match") === "fake-etag") {
      set.status = 304;
      return;
    } else if(modifiedSince && new Date(modifiedSince) >= modificationDate) {
      set.status = 304;
      return;
    } else {
      return {
        hello: "world"
      }
    }
  }
```

Here is the wretch client call:

```ts
const result = await wretch()
  .accept("application/json")
  .get("/resource")
  .json();
console.log(`response: `, result)
```

The browser adds the headers and retrieves the response from the cache:

<img width="1372" alt="Capture d’écran 2023-09-12 à 18 46 51" src="https://github.com/elbywan/wretch/assets/3428394/25224686-4ecb-4d1c-806a-965bf802fd40">

And wretch is successfully parsing the json:

<img width="343" alt="Capture d’écran 2023-09-12 à 18 54 14" src="https://github.com/elbywan/wretch/assets/3428394/8ec64ef0-0b88-482d-a0cf-b25b96f1e36e">
