### ISSUE TITLE
Addon for upload progress

### ISSUE THREAD

**Issue by kibertoad** [elbywan/wretch#199]
Is it possible to have something similar to https://github.com/elbywan/wretch#progress- for the upload progress?

This is for implementing upload progress indicators.
Something like this: https://github.com/axios/axios/blob/main/examples/upload/index.html

**Comment by elbywan** [comment]
Hey @kibertoad,

> s it possible to have something similar to https://github.com/elbywan/wretch#progress- for the upload progress?

Unfortunately no, this is a limitation of using fetch :/.

See: https://github.com/elbywan/wretch/issues/154

**Comment by kibertoad** [comment]
@elbywan document linked in that issue states that everything but firefox support it, and firefox has miniscule market share. is it still too early for this feature?

**Comment by elbywan** [comment]
Hey @kibertoad,

I think the link you are referring to is about the `Request.body` field and yeah Firefox does not support that.

In addition, Safari does not support upload streaming which is a bit different (passing the body as a readable stream to fetch):

```js
fetch("/", {
  method: 'POST',
  headers: {'Content-Type': 'text/plain'},
  body: stream, // a previously constructed stream
  duplex: 'half',
});
```

Gives:

`notsupportederror: ReadableStream uploading is not supported`

> is it still too early for this feature?

Yes I think it would be better to wait or proper support - and a proper API.

**Comment by kibertoad** [comment]
There is https://github.com/whatwg/fetch/issues/607, apparently.
