### ISSUE TITLE
Ability to set baseUrl

### ISSUE THREAD

**Issue by chimon2000** [elbywan/wretch#2]
It would be nice to be able to set a baseUrl in the defaults, similar to how you can in axios:

```
var instance = axios.create({
  baseURL: 'https://api.example.com'
});
```

Awesome work, this library is just what I have been looking for!

**Comment by elbywan** [comment]
> Awesome work, this library is just what I have been looking for!

Thanks !

> It would be nice to be able to set a baseUrl in the defaults, similar to how you can in axios:

This is just the feedback I need, I will implement it this morning 😄

**Comment by elbywan** [comment]
Just implemented the functionality but in a slightly different way as I prefer immutability over global options ;).

```js
// Subsequent requests made using the 'blogs' object will be prefixed with "http://mywebsite.org/api/blogs"
const blogs = wretch().baseUrl("http://mywebsite.org/api/blogs")

// Perfect for CRUD apis
const id = await blogs("").json({ name: "my blog" }).post().json(_ => _.id)
const blog = await blogs(`/${id}`).get().json()
console.log(blog.name)
await blogs(`/${id}`).delete()
// ... //
```

Hope it suits your needs !

**Comment by chimon2000** [comment]
That is awesome, thanks for the quick turnaround
