### ISSUE TITLE
Wrong condition in FormDataAddon and not converting FileList to `file[]` format

### ISSUE THREAD

**Issue by hamidreza4dev** [elbywan/wretch#201]
Hi,
the problem is that FileList is not an instance of Array and this will cause an issue.

https://github.com/elbywan/wretch/blob/411fb09d218fe997dfb3274453953594008e54ce/src/addons/formData.ts#L15

it can simply be fixed by changing the condition to:
```js
if (value instanceof Array || value instanceof FileList) {
// ...    
```

**Comment by elbywan** [comment]
Hey @hamidreza4dev,

Thanks for raising the issue 🙇.

I just published [`v2.7.0`](https://github.com/elbywan/wretch/releases/tag/2.7.0) which now supports passing `FileList` instances to the form data addon.
