### ISSUE TITLE
I get an error when I try to get an ArrayBuffer 

### ISSUE THREAD

**Issue by kravetsone** [elbywan/wretch#202]
```ts
.catcherFallback(async (error) => {
        console.log("errrorrrr", await error.response.arrayBuffer());
    });
```
When i try to get ArrayBuffer like this i recieve a error:

![image](https://github.com/elbywan/wretch/assets/57632712/4aa0e465-c048-4365-b118-a6c94295e8d6)

WretchError is 
```ts
export declare class WretchError extends Error implements WretchErrorType {
    status: number;
    response: WretchResponse;
    url: string;
    text?: string;
    json?: any;
}
```
how can i get ArrayBuffer?

**Comment by elbywan** [comment]
Hey @kravetsone,

> When i try to get ArrayBuffer like this i recieve a error:

This is expected since wretch already reads the error payload body to fill the WretchError instance for easier consumption. It is a stream and can be read only once.

I guess you could try the following:

```js
.catcherFallback(async (error) => {
  console.log("errrorrrr", await new Response(error.text).arrayBuffer());
});
```

**Comment by kravetsone** [comment]
maybe a better way would be
```ts
.catcherFallback(async (error) => {
  await error.text();
  await error.json();
  await error.arrayBuffer();
});
```
It's look like work with successful response and more convenient in my opinion

**Comment by elbywan** [comment]
Wretch parses the response body as a string - or json (depending on the content-type) ahead of time to pre-populate the `WretchError` fields for convenience and prevent having to perform asynchronous operations after catching it. 

I could clone the response body stream to make it consumable twice, but then it would consume more memory.

So I am comfortable with the current way of doing things, since having arrayBuffer/blob error payloads is quite uncommon compared to text/json.

**Comment by kravetsone** [comment]
in my project, I use protocol buffers and when I follow your example above during deserialization, I get an EOT (End Of File) error, although this does not happen with successful requests.

I do not know what to do(

**Comment by kravetsone** [comment]
Thanks for the quick help! I repeated all the steps and found the problem. The problem was in the wrong way to serialization validation errors)

it's ugly... but it's work!
![image](https://github.com/elbywan/wretch/assets/57632712/5586aaee-04c5-460c-bc45-c95b7c3237cb)

By the way, TextEncoder does not accept such a parameter and works with UTF-8 by default.  But thanks anyway!
![image](https://github.com/elbywan/wretch/assets/57632712/2a3e5b2d-a0c8-4dc4-bd9c-86cf9b765bea)
