### ISSUE TITLE
Will this API work with the React 18 and/or NextJS extension to the fetch API?

### ISSUE THREAD

**Issue by heath-freenome** [elbywan/wretch#203]
We use `wretch`  with a MobX-based store system on our own home-grown SSR implementation. We are in the process of upgrading to `React 18` and are planning to also switch to using NextJS. I want to keep my MobX store system if at all possible. After reading the NextJS [data fetching documentation](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#fetching-data-on-the-server-with-fetch) I learned that both React and NextJS are extending `fetch`. I was wondering whether this library will just automatically pick up these extensions?

**Comment by elbywan** [comment]
Hey @heath-freenome,

>  I was wondering whether this library will just automatically pick up these extensions?

I cannot say for sure but I do not see any reason why it would not work as expected since wretch is just a wrapper around whatever fetch is provided by the platform.

```js
// For instance to use the nextjs custom options:
wretch(…).options({ 
  next: { 
    revalidate: 3600,
    tags: ['collection' ]
  } 
})
```

**Comment by heath-freenome** [comment]
Awesome! Great library BTW!
