### ISSUE TITLE
fetchError not being called

### ISSUE THREAD

**Issue by Hrishikesh-K** [elbywan/wretch#207]
Hey! Thanks so much for working on this project, it's a lifesaver!

Regarding the issue, I have referred to:

https://github.com/elbywan/wretch/issues/162
https://github.com/elbywan/wretch/issues/111
https://github.com/elbywan/wretch/issues/62

The goal is to catch any network error. So `fetchError` seems to be the correct way to do that. I have my code like:

```js
const res = await wretch('https://www.example.com/404').get().fetchError(error => {
  console.log('error from fetchError')
}).text()
```

This throws a HTTP 404, so it should have been available in `fetchError`. But, it's not. It throws an uncaught exception. Based on this comment: https://github.com/elbywan/wretch/issues/111#issuecomment-877763857, this seems to be expected behaviour. So, I'm just supposed to move my `fetchError` to the end, except that doesn't work:

![image](https://github.com/elbywan/wretch/assets/11403551/7a09f00f-e3e6-4288-a069-7e0af70712cc)

I get "Unresolved function or method fetchError()".

So, I tried to use `catch()` after my `text()`. But that breaks my response as my response now gets `string | void` type. I then have to check for the response everytime before processing. Furthermore, I don't get the status code as `error.status` if I use `catch()`.

I'm sure I'm mixing up some concepts and confusing myself, but all I need is:

1. Catch only network errors
2. Capture the status code received from the server
3. Keep my response type intact (not add a `void` type)

What am I missing?

**Comment by elbywan** [comment]
Hey @Hrishikesh-K,

> Hey! Thanks so much for working on this project, it's a lifesaver!

Thanks a bunch! 🙇 

> What am I missing?

I think that what you are looking for is [`.catcherFallback()`](https://elbywan.github.io/wretch/api/interfaces/index.Wretch.html#catcherFallback).

[`.fetchError()`](https://elbywan.github.io/wretch/api/interfaces/index.WretchResponseChain.html#fetchError) is used to catch [errors thrown by the fetch function itself](https://developer.mozilla.org/en-US/docs/Web/API/fetch#exceptions), including "network errors" which are related to habing issues reaching the server (being offline for instance) - and they are unrelated to http codes. 

The correct syntax would be:

```js
wretch("https://jsonplaceholder.typicode.com")
  .catcherFallback((err) => console.log("http error", err))
  .get("/posts")
  .fetchError((error) => console.log("network error", error))
  .json(console.log);
```

**Comment by Hrishikesh-K** [comment]
That was it, thanks!
