### ISSUE TITLE
onAbort on instance

### ISSUE THREAD

**Issue by Hrishikesh-K** [elbywan/wretch#208]
I have a feeling this is a simple thing, but I'm missing it fairly easily.

My code:

```js
import {env} from 'node:process'
import wretch from 'wretch'
import wretchAbort from 'wretch/addons/abort'
import wretchQueryString from 'wretch/addons/queryString'
export const wretchInstance= wretch('https://www.example.com/').addon(wretchAbort()).addon(wretchQueryString).auth(`Basic ${btoa(`${env['USERNAME']}:${env['PASSWORD']}`)}`)
export function abortHandler() {
  // do stuff
}
```

I am using that instance multiple times. Each time, I need to write it like:

```js
wretchInstance.signal(request.abortController).get().onAbort(abortHandler).text()
```

It works, but I am having to repeat myself everytime and it's very easy to forget adding it. Is it possible to use `onAbort` before `.get()` (or any other method), so it's directly on the instance? Every example I've seen about this has the `.onAbort()` after the method.

**Comment by elbywan** [comment]
> Is it possible to use onAbort before .get() (or any other method), so it's directly on the instance?

No, but you can should be able to use [`.resolve()`](https://elbywan.github.io/wretch/api/interfaces/index.Wretch.html#resolve) to append it automatically:

```js
export const wretchInstance= wretch('https://www.example.com/')
  .addon(wretchAbort())
  .addon(wretchQueryString)
  .auth(`Basic ${btoa(`${env['USERNAME']}:${env['PASSWORD']}`)}`)
  .resolve(resolver => resolver.onAbort(abortHandler))
```

**Comment by Hrishikesh-K** [comment]
Perfect ❤️ !
