### ISSUE TITLE
.then() is also called on caught errors

### ISSUE THREAD

**Issue by Hrishikesh-K** [elbywan/wretch#209]
Sorry for back to back issues!

Not sure if this is expected, but:

```js
import wretch from 'wretch'
wretch('https://www.example.com/404').get().notFound(() => {
  console.log('404 callback')
}).text(() => {
  console.log('text callback')
}).then(() => {
  console.log('then callback')
})
```

returns this console output:

```
404 callback
then callback
```

I'd have expected `.then()` to not be called if any error occurs (and is caught) before. This is causing my application to fail.

In my app, if I use something like:

```ts
wretch('/api/user/info').catcherFallback(() => {
  loginErr.value = true
}).get().forbidden(() => {
  // forbidden is an expected error if a user is logged out,
  // I don't wish to do anything here
  console.log('forbidden')
}).fetchError(() => {
  // but I wish to catch any other fetch error or HTTP error
 // as done in the `catcherFallback()` block above
  loginErr.value = true
}).json<{
  ntl : TNUser
  zd : TZUser
}>(userRes => {
  // if I use it here, it won't cause an issue and I'd be able to ensure that this part
  // executes only when the fetch is successful, but this gives me a TS error as shown
  // in the screenshot after this code block
  userNtl.value = userRes.ntl
  userZd.value = userRes.zd
})
```

![image](https://github.com/elbywan/wretch/assets/11403551/1ef1cf36-9e3c-4241-aaf4-a8503ed0ad23)

To avoid this TS error, I am using the values in `.then()` after `.json()`, but that's being called even after the expected 403 error.

Is this supposed to happen? Based on this area in the readme: https://github.com/elbywan/wretch?tab=readme-ov-file#catchers-

![image](https://github.com/elbywan/wretch/assets/11403551/13daaaa3-e1f9-47b1-bb6c-3a6caa2f4cef)

`.then()` is supposed to execute only on the result, but I might have misunderstood something.

**Comment by elbywan** [comment]
Hey again @Hrishikesh-K,

> Sorry for back to back issues!

No worries 😄.

> I'd have expected .then() to not be called if any error occurs (and is caught) before. This is causing my application to fail.

> .then() is supposed to execute only on the result, but I might have misunderstood something.

[This is actually how javascript promises work](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Using_promises#chaining_after_a_catch) - and what I meant in the comment by `The promise chain is preserved`.
It is also very useful when you want to catch errors, perform some action and return an alternate payload down the chain.

```js
new Promise((res, rej) => rej("Error"))
  .then(_ => { console.log("never called"); return 0 })
  .catch(err => { console.log('caught'); return 1 })
  .then(console.log) // => 1
```

If you want to propagate the error you can just rethrow it:

```js
new Promise((res, rej) => rej("Error"))
  .then(_ => { console.log("never called"); return 0 })
  .catch(err => { console.log('caught'); throw err }) // <= rethrow the error
  .then(console.log)
// => Uncaught (in promise) Error
```

**Comment by Hrishikesh-K** [comment]
Interesting. I wasn't used to chaining so many promises like this, so for me:

```js
fetch().then(() => {
  // would execute only if successful
}).catch(() => {
  // would execute only if error
})
```

was what I had in my mind! Thanks for the clarification!
