### ISSUE TITLE
[QUESTION] How can I add generic here?

### ISSUE THREAD

**Issue by kravetsone** [elbywan/wretch#213]
How can I add generic here?

```ts
import type { WretchAddon, WretchResponseChain } from "wretch"

export interface SomeAddon {
    test: <T, C extends MsgpackAddon, R>(
        this: T & WretchResponseChain<T, C, R>
      ) => any; // insted of any - generic
}

export const SomeAddon: WretchAddon<unknown, SomeAddon> = {
    resolver: {
        test: async function () {
           // some logic
        }
    }
}
```

I want to use it like this

wretch().post().test<{some: "value"}>();

ReturnType - {some: "value"}

**Comment by elbywan** [comment]
Hey @kravetsone,

> How can I add generic here?

I don't think you can. Typescript needs more info to be able to infer the return type, like linking the generic type to an argument of the function.

**Comment by kravetsone** [comment]
Why? I need a custom addon with analog of .json<type>(); and I can't do it?(

**Comment by elbywan** [comment]
.json bases the return type on the callback argument

**Comment by kravetsone** [comment]
> `.json` uses the return type of the callback argument linked with the generic. 
> `<Result = void>(cb?: (type: Type) => Result) => Promise<Awaited<Result>>`
> 
> Anyway this is not related to wretch at all, you should maybe check typescript related forums.

But i talk about how to pass generic to my function from addon...

```ts
import type { WretchAddon, WretchResponseChain } from "wretch"

export interface SomeAddon {
    test: <T, C extends MsgpackAddon, R, Res>(
        this: T & WretchResponseChain<T, C, R>
      ) => Promise<Res>;
}

export const SomeAddon: WretchAddon<unknown, SomeAddon> = {
    resolver: {
        test: async function () {
           
        }
    }
}
```

```ts
wretch().post().test<{some: "value"}>();
//^ mising type parameters and i don't know how to make it so that there is 1 argument - which will indicate the result of the method
```
You can't show an example of implementing a function similar to .json(); but in adon? I want the user to be able to specify with a generic argument what will be returned to him

**Comment by elbywan** [comment]
> You can't show an example of implementing a function similar to .json(); but in adon? I want the user to be able to specify with a generic argument what will be returned to him

As I said I don't think it is possible to do this - no matter the context.

```ts
function fun<Return>() : Return {
  return 1
}
/*
Type 'number' is not assignable to type 'Return'.
  'Return' could be instantiated with an arbitrary type which could be unrelated to 'number'.ts(2322)
*/
```

**Comment by kravetsone** [comment]
I want to write an addon that serializes/deserializes data... I understand how to write it, but I don't understand how to allow specifying the type.test<{some: 2}>(); as I understand it, this is not possible in the current implementation of addons?


> > You can't show an example of implementing a function similar to .json(); but in adon? I want the user to be able to specify with a generic argument what will be returned to him
> 
> As I said I don't think it is possible to do this with the function signature in your example - no matter the context.
> 
> ```ts
> function fun<Return>() : Return {
>   return 1
> }
> /*
> Type 'number' is not assignable to type 'Return'.
>   'Return' could be instantiated with an arbitrary type which could be unrelated to 'number'.ts(2322)
> */
> ```
> 
> Unless you cast the return type explicitely:
> 
> ```js
> function fun<Return>() : Return {
>   return 1 as Return
> }
> ```

I don't understand what does this have to do with it? I'm asking about how to make a generic that the user can specify. Without it, my method will not be convenient
And <T, C extends MsgpackAddon, R> are bothering me. Because the argument turns out to be 4
I don't understand how to do this in wretch and not in typescript
