### ISSUE TITLE
Handling 302 redirects

### ISSUE THREAD

**Issue by ampossardt** [elbywan/wretch#215]
Hello, really loving wretch so far after using axios for so many years just by default. I ran into a rather specific scenario that I have handled, but I think it could be handled better or more elegantly. Essentially, I have a backend that acts as a BFF which handles all of my authentication, and it returns 302s when the user isn't authenticated which redirect to Auth0 for login. I have an initial call within my front-end that fetches user info, and this call will 302 initially if the user isn't logged in. I'm wondering what the best way to handle this within wretch is.

My current solution is to catch the error generically and redirect the user manually:
```
const api = wretch(`${process.env.NEXT_PUBLIC_API_V2_URL}`)
  .options({ credentials: "include", mode: "cors", redirect: "manual" })
  .catcherFallback((err) => {
    if (!err.status || err.status === 0) {
      redirectToLogin();
    }
  });

// API call to user info used in other places
await api.get("/account/userinfo").json()
```

The reason I'm checking if status is falsy is due to a weird bug where the error returned here doesn't actually contain a status code. I can see its a 302 in the dev tools, but for some reason it seems fetch itself isn't able to capture and pass along that info. If I allow the `redirect` prop to be the fetch default (follow), I get the error `TypeError: NetworkError when attempting to fetch resource.` as the entire WretchError object that's passed, so still no other info like the response type.

Is there a better method that I can use to handle this? Or is there something I'm missing here in regards to how fetch/wretch are working? As I previously said, my code works pretty much as expected in this scenario but I am a bit uneasy about not being able to actually verify that the response of the network call was a 302 and needing to send the user back to login by default.

**Comment by elbywan** [comment]
Hey @ampossardt,

> really loving wretch so far after using axios for so many years just by default

Thanks! 🙇 

> Is there a better method that I can use to handle this?

I think using a middleware could be more suited:

```js
const api = wretch(`${process.env.NEXT_PUBLIC_API_V2_URL}`)
  .options({ credentials: "include", mode: "cors", redirect: "manual" })
  .middlewares([
    (next) => (url, opts) => {
      return next(url, opts).then(res => {
        if (res.status === 302) {
          redirectToLogin();
        }
        return res
      })
    }
  ])
```
