### ISSUE TITLE
Unable to resolve any addon in Expo React Native project

### ISSUE THREAD

**Issue by thisisomar** [elbywan/wretch#218]
Hey there! 

I am having a weird issue when using the FormDataAddon or even any addon for that matter with Wretch in a React Native Expo (with TypeScript) project. 

I get this error on attempting to import an addon (this happens when running the project)
```
Unable to resolve "wretch/addons/formData" from "api/api.ts"
```

I've created a reproducible example [here](https://github.com/thisisomar/wretch-expo-repro). This is the Expo RN TypeScript template - I am using Node 18.16.0.

I tried spending a bit of time to look into the issue, and I discovered that specifying the full relative path works completely fine:
```
import FormDataAddon from "../node_modules/wretch/dist/addons/formData"
```
So I presume this may be an issue with Expo's bundling?

**Comment by elbywan** [comment]
Hey @thisisomar, thanks for reporting the issue 👍 

> So I presume this may be an issue with Expo's bundling?

Yes, more specifically with the metro bundler [which does not support package exports by default](https://metrobundler.dev/docs/package-exports/).

It seems to work fine on my end [when customizing the config file](https://docs.expo.dev/guides/customizing-metro/):

```bash
# will generate a metro config file:
npx expo customize metro.config.js
```

```js
// Learn more https://docs.expo.io/guides/customizing-metro
const { getDefaultConfig } = require('expo/metro-config');

/** @type {import('expo/metro-config').MetroConfig} */
const config = getDefaultConfig(__dirname);
config.resolver.unstable_enablePackageExports = true; // <- ADD THIS

module.exports = config;
```

**Comment by thisisomar** [comment]
Hey thanks for the speedy response, appreciate it! I see, yeah this is what I was thinking

I tried enabling this in the repro I provided and it works, but doing this in my main project with other packages installed (react query, react hook forms to name a couple as they're the ones complaining), my project fails to run so I am not sure if this is a viable solution.

Is there an alternative here?

**Comment by elbywan** [comment]
> Is there an alternative here?

You could try using a [custom resolver](https://metrobundler.dev/docs/configuration/#resolverequest) in the metro config:

```js
config.resolver.resolveRequest = (context, moduleName, platform) => {
  if (moduleName.startsWith('wretch/addons')) {
    return {
      filePath: require.resolve(moduleName),
      type: 'sourceFile',
    };
  }
  return context.resolveRequest(context, moduleName, platform);
}
```

**Comment by thisisomar** [comment]
Ahh yeah this works, thanks - good time to get myself familiar with Metro bundling. I think we can close this issue out, hopefully someone else will find this helpful - I will let you close it if you think everything is good on your end
