### ISSUE TITLE
Difference between middleware / resolvers

### ISSUE THREAD

**Issue by dredzone** [elbywan/wretch#22]
First, great little library thanks for the work.

Question, what is main diference between middleware / resolvers, when one should be used vs another? 

Thanks.

**Comment by elbywan** [comment]
> First, great little library thanks for the work.

Thanks !

>Question, what is main diference between middleware / resolvers, when one should be used vs another?

Middleware are used to perform an actions **before** the request is performed.
Resolvers are used to program a chain of actions to perform **after** the request has completed.

Examples:

*Before the request*

```js
/* A simple delay middleware. */
const delayMiddleware = delay => next => (url, opts) => {
  return new Promise(res => setTimeout(() => res(next(url, opts)), delay))
}

// The request will be delayed by 1 second.
wretch("...").middlewares([
  delayMiddleware(1000)
]).get().res(_ => /* ... */)
```

*After, on the response*

```js
// Program "response" chain actions early on
const w = wretch()
  .resolve(resolver => resolver
    .perfs(_ =>  /* monitor every request */)
    .json(_ => _ /* automatically parse and return json */))

const myJson = await w.url("http://a.com").get()
// Equivalent to wretch()
//  .url("http://a.com")
//  .get()
//     <- the resolver chain is automatically injected here !
//  .perfs(_ =>  /* ... */)
//  .json(_ => _)
```

**Comment by dredzone** [comment]
Thanks for quick response, 

But middleware also has access to response object, see below snippet, can resolver logic go in there?

```
const middleware = () => next => (url, opts) => {
  return eturn next(url, opts).then(response => {
   // perform resolve logic
  });
}
```

**Comment by dredzone** [comment]
Thanks for quick responses.
