### ISSUE TITLE
How to send (object manually converted to) FormData instance?

### ISSUE THREAD

**Issue by Gildedter** [elbywan/wretch#220]
I have the following object (this is a smaller example where `checklist` only has one item, there may be more):
```
{
  "checklist": [
    { "areaCode": "4FLR", "areaName": "4TH FLOOR",
      "subAreas": [
        { "subAreaCode": "CLINIC","subAreaName": "Clinic",
          "checklist": [
            { "areaId": 1315, "itemCode": "BED", "itemName": "Bed", "remarks": null,
              "level": 1, "listStatus": false, "checked": true
            },
            { "areaId": 1316, "itemCode": "BLINDS", "itemName": "Blinds", "remarks": null,
              "level": 1, "listStatus": false, "checked": true,
              "files": { // this is supposed to be a FileList, I can't seem to copy it from console.log
                "0": {} 
              }
            },
            { "areaId": 1317, "itemCode": "ARTPLANT", "itemName": "Artificial Plant", "remarks": null,
              "level": 2, "listStatus": true, "checked": true,
              "files": { // this is supposed to be a FileList, I can't seem to copy it from console.log
                "0": {}
              }
            }
          ],
          "checked": true,
          "timeChecked": "01:05 PM"
        }
      ],
      "checked": true,
      "timeChecked": "03-01-2024 01:04 PM"
    }
  ]
}
```

currently the FormDataAddon returns [object Object] on 3 to 4 deep nested object (they all have object arrays as a property)
I passed it directly like so:
```
const api = wretch().addon(FormUrlAddon).addon(FormDataAddon).addon(QueryStringAddon).middlewares([dedupe()]).errorType('json')

const payload = {checklist:[...dataSource]};

await api .url(`api/send-payload`)
.formData(payload )
.post()
// etc...
```

Looking at the request log in my browser's dev tools:
```
Content-Disposition: form-data; name="checklist"

[object Object]
```

**Comment by elbywan** [comment]
Hey @Gildedter,

`formData` accepts a second argument to make it recursive which is false by default.

`formData<T, C, R>(this, formObject, recursive?): FormDataAddon`
(https://elbywan.github.io/wretch/api/interfaces/addons_formData.FormDataAddon.html)

> The recursive argument when set to true will enable recursion through all nested objects and produce object[key] keys. It can be set to an array of string to exclude specific keys.

Could you try with it toggled on?

```js
.formData(payload, true)
```

**Comment by Gildedter** [comment]
> Hey @Gildedter,
> 
> ~`formData` accepts a second argument to make it recursive which is false by default.~
> 
> `formData<T, C, R>(this, formObject, recursive?): FormDataAddon` (https://elbywan.github.io/wretch/api/interfaces/addons_formData.FormDataAddon.html)
> 
> > The recursive argument when set to true will enable recursion through all nested objects and produce object[key] keys. It can be set to an array of string to exclude specific keys.
> 
> ~Could you try with it toggled on?~
> 
> ```js
> .formData(payload, true)
> ```
> 

I tried it, but I'm still getting the same `[object Object]` on the request log
![image](https://github.com/elbywan/wretch/assets/93777256/9cb057f5-cb57-4cae-8bb6-35f80baf71e3)

**Comment by elbywan** [comment]
Allright so after double checking it seems like the FormData serializer does not support nested arrays, only objects.

I believe it was done this way because it is complicated to assess if an array needs to be recursively serialized or appended as-is. And it varies depending on the platform (Blobs / Buffers / Files…).

Sorry about this 🙇.

I'll try to check if it is possible to implement this when I have some free time.
In the meantime, you can write your own serliazer that suits you needs (or use a 3rd party?) and then pass the FormData object with .body:

```js
const serializedPayload = serialize(payload); // returns a FormData

await api .url(`api/send-payload`)
  .body(serializedPayload) // should be enough to set the right content type header
  .post()
  …
```

**Comment by Gildedter** [comment]
will do, thank you, I'm using the browser at the moment, since my back end is written in php

**Comment by Gildedter** [comment]
will do, thank you, I'm using the browser at the moment, since my back end is written in php
