### ISSUE TITLE
Basic auth middleware/extension

### ISSUE THREAD

**Issue by BendingBender** [elbywan/wretch#221]
Would you be interested in a basic auth middleware/extension? Currently, if a URL contains basic auth credentials `fetch` and by extension `wretch` will just throw an error.

The middleware I'd like to implement would extract the username/pw from the URL and add them as an `Authorization` header.  
The extension could provide a `basicAuth` method so that users don't have know how to construct a basic auth header themselves.

**Comment by elbywan** [comment]
Hey @BendingBender 👋 

> Would you be interested in a basic auth middleware/extension? 

This would be a good addition 👍 

I don't have much spare time but I can give it a bite next week end.
