### ISSUE TITLE
wretch and nextjs caching

### ISSUE THREAD

**Issue by gutisalex** [elbywan/wretch#227]
I am curious if I still have all the caching benefits nextjs 14 offers when I use  wretch? Using fetch in nextjs does all the caching... When using wretch, do I have to setup my own caching or is it using fetch from nextjs?

**Comment by alex4brandung** [comment]
it seems I have... I can just pass the next specific options mentioned in the docs! So this can be closed...

**Comment by gutisalex** [comment]
it seems I have... I can just pass the next specific options mentioned in the docs! So this can be closed...
