### ISSUE TITLE
No nice way to handle 202 Accepted

### ISSUE THREAD

**Issue by voronaam** [elbywan/wretch#228]
We were pretty happy with a nice 

```
api.post(content)
  .json()
  .then((responseBody) => {...})
```

Until the backend added a feature to process large requests in the background. In which case the API return `HTTP 202 Accepted` and no body.

I tried to catch it with `.error(202, (res) => {...})` but since 202 is not a error response, it did not work.

In the end I had to resort to the raw response handling as in:

```
api.post(content)
  .res((raw_response) => {
    if (raw_response.status === 202) {
      notifyUser('background processing');
      return;
    }
    raw_response.json().then((responseBody) => {...})
  });
```

The actual code is a bit more ugly because of extra `.catch(...)` everywhere.

Is there a more wretch-like way to handle the 202 response status?

**Comment by elbywan** [comment]
Hey @voronaam, sorry for the late answer.

> Is there a more wretch-like way to handle the 202 response status?

One way of doing this would be to add a tiny middleware which throws a custom error on 202s and catch it:

```ts
class NoContentError extends Error {
  name = 'NoContentError';
  message = '202 No Content';
}

const api = wretch(`https://httpstat.us`)
  .middlewares([next => async (url, opts) => {
    const res = await next(url, opts);
    if (res.status === 202) {
      throw new NoContentError()
    }
    return res;
  }])
  .catcher("NoContentError", (error) => {
    console.log(error.message)
  })

api.url('/200')
  .post({ hello: "world" })
  .text((responseBody) => {
    console.log(responseBody)
  })

api.url('/202')
  .post({ hello: "world" })
  .text((responseBody) => {
    console.log(responseBody)
  })
```

**Comment by voronaam** [comment]
Thank you!
