### ISSUE TITLE
Having an issue with setting timeouts

### ISSUE THREAD

**Issue by lantrix** [elbywan/wretch#23]
If I do a simple POST I have no problems:

```javascript
wretch(url)
  .json(jsonMessage)
  .post()
  .res()
  .catch(error => console.log(error))
```

The moment I try to use the timeout syntactic sugar (and setting a timeout) like this:

```javascript
wretch(url)
  .json(jsonMessage)
  .post()
  .setTimeout(1000)
  .timeout(err => console.log(err.status))
  .res()
  .catch(error => console.log(error))
```

I get the following error and I can't figure out why:

    TypeError: Cannot read property 'abort' of undefined
    resolver.ts:128
        at Timeout._onTimeout (/Users/ebuchan/Source/Repos/slackapp-ops/node_modules/wretch/dist/bundle/wretch.js:1:4954)
        at ontimeout (timers.js:498:11)
        at tryOnTimeout (timers.js:323:5)
        at Timer.listOnTimeout (timers.js:290:5)

**Comment by elbywan** [comment]
@lantrix Hi !

the `.timeout()` function depends on the support of [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController).

Can you check that the browser you are using supports this? 
If not, or if using node.js you try with a [polyfill](https://www.npmjs.com/package/abortcontroller-polyfill)? (it won't really abort the request, but oy won't get any error and the callback will be called anyway)

Thanks!

**Comment by lantrix** [comment]
Yeah I've missed that in the doco. I'm using Node.JS and will try out what you suggested with a polyfill.

**Comment by lantrix** [comment]
Yes that worked. Thanks for the help.

```javascript
const wretch = require('wretch');
const { AbortController, abortableFetch } = require('abortcontroller-polyfill/dist/cjs-ponyfill');
const { fetch } = abortableFetch(require('node-fetch'));
wretch().polyfills({
	fetch,
	AbortController
});
```
