### ISSUE TITLE
Not clear how to type a precomposed Wretch object

### ISSUE THREAD

**Issue by Offlein** [elbywan/wretch#239]
Hi, I feel like I've struggled with this for a while and I'm not sure if the methodology I'm using is correct.

We have multiple frontend apps that used Wretch, and they are all preconfigured my apps' bootstrap functions using a shared configuration module. 

My apps, at least, are Vue, and we use Vue's "provide/inject" functionality to configure Wretch, "provide" it to any child components, and then I "inject" the configured Wretch object in the components, 

The trick is that the configured Wretch object isn't just "wretch", it's "wretch + plugin[s]".

I had a hassle figuring out the proper way to type it, but in the end, I'm using this:

```ts
import { Wretch } from 'wretch'
import type { QueryStringAddon } from "wretch/addons/queryString"
const http = inject('my-preconfigured-wretch') as Ref<QueryStringAddon & Wretch<QueryStringAddon>>
```

I think this works but I don't see any official instruction on this, and my IDE won't autocomplete an exported `QueryStringAddon` from that `wretch/addons/queryString` package for some reason. (It DOES autocomplete it from `wretch/bundle/addons/addons`, but this throws an error when the app launches?)

Anyway, just looking for confirmation; and it feels like it may help people in the future? Or I'm weird. Either way, thank you. :)

**Comment by elbywan** [comment]
Hey @Offlein 👋,

> my IDE won't autocomplete an exported QueryStringAddon from that wretch/addons/queryString package for some reason  (It DOES autocomplete it from wretch/bundle/addons/addons, but this throws an error when the app launches?)

I tried with the following imports but they all work on my side:

```ts
import { queryStringAddon } from 'wretch/addons';
import queryStringAddon from 'wretch/addons/queryString'
import type { QueryStringAddon } from 'wretch/addons';
import type { QueryStringAddon } from 'wretch/addons/queryString';
```


> I had a hassle figuring out the proper way to type it, but in the end, I'm using this (…)

Did you try using `typeof` to infer and export the type? Something like:

```ts
// http.ts
import wretch from 'wretch';
import QueryStringAddon from 'wretch/addons/queryString';

export const http = wretch('https://jsonplaceholder.typicode.com').addon(QueryStringAddon);
export type Http = typeof http;
```

```vue
// xxx.vue
<script setup lang="ts">
import { inject } from 'vue';
import { Http } from './http';

const http = inject('http') as Http;
console.log(http.query) // function query(qp, replace, omitUndefinedOrNullValues) { … }
</script>
```

<img width="781" alt="Capture d’écran 2024-07-06 à 09 51 51" src="https://github.com/elbywan/wretch/assets/3428394/dc877836-57cb-4b64-b40f-affbfe56f202">

**Comment by Offlein** [comment]
@elbywan Thank you for your time. 

>I tried with the following imports but they all work on my side:

I think this must be simply an issue with my configuration. :( I'm working in an old, legacy app that was converted into a monorepo with multiple frontend apps and a new backend placed maybe suboptimally in the root of the codebase. I had a great deal of time getting my Vite and tsconfig configurations in general to identify files where they're intended to be and I suspect this issue is somehow an outgrowth of this? 

>Did you try using `typeof` to infer and export the type? Something like:

No! That's a very astute proposal, though; thank you. While looking into trying this, it looks like at some point I also asserted the type of my configured wretch object as simply `Wretch` -- I assume when I was most in the dark with my workspace configuration. Overlooking this surely could've stymied my other efforts to properly infer the type here as well. So this looks like a problem of my own creation.

I greatly appreciate your time and patience; thank you so much for weighing in. This is all good now.
