### ISSUE TITLE
Is it possible to recognize fetch error type?

### ISSUE THREAD

**Issue by enthusiast17** [elbywan/wretch#241]
I would like to recognize fetch error on .catch level. Is it possible?

```js
wretch()
.get('/something')
.fetchError((error) => {
  throw error;
})
.res(() => null)
.catch((error) => {
  if (isFetchError(error)) {
  
  }
  
  throw error;
});
```

**Comment by elbywan** [comment]
Hey @enthusiast17,

> Is it possible?

Yes, by asserting that the error is not thrown by `wretch` itself. 

```js
.catch((error) => {
  if (!(error instanceof WretchError)) {
    // likely a fetch error
  }
  
  throw error;
});
```

_PS: I recommend using the [.fetchError()](https://elbywan.github.io/wretch/api/interfaces/index.WretchResponseChain#fetchError) catcher which has been made for this purpose._
