### ISSUE TITLE
Svelte +page.ts using wretch

### ISSUE THREAD

**Issue by mispp** [elbywan/wretch#242]
Is it possible to use wretch in sveltekit's +page.ts?

Sveltekit, being a framework, has some conventions, one of which is how to preload data for a given page.
During this pageload event, svelte kit uses following function signature 

```javascript
export const load: PageLoad = async ({ fetch }: LoadEvent) => {}
```

If `fetch` provided in the closure is not used to actually pull data from some endpoint, JavaScript console complains for not using this one, but rather defaults to window fetch.

Since wretch wraps around `fetch`, is it possible to provide and 'external' fetch that it would wrap?

Or in other words, can `fetch` be passed to wretch via `.options` and `replace` so it would wrap?

To be honest I do not know how exactly `fetch` provided by sveltekit in the closure is different to calling fetch on its own.

**Comment by elbywan** [comment]
Hey @mispp,

> can fetch be passed to wretch via .options and replace?

I am not familiar with svelte at all but based on your excellent description I would suggest using the [`.polyfills({ fetch })`](https://elbywan.github.io/wretch/api/interfaces/index.Wretch#polyfills) method.

**Comment by mispp** [comment]
> Hey @mispp,
> 
> > can fetch be passed to wretch via .options and replace?
> 
> I am not familiar with svelte at all but based on your excellent description I would suggest using the [`.polyfills({ fetch })`](https://elbywan.github.io/wretch/api/interfaces/index.Wretch#polyfills) method.

I've updated the question to make it epic. Does it make sense now?

**Comment by elbywan** [comment]
> is it possible to provide and 'external' fetch that it would wrap?

Yes, using the `.polyfills` method that I linked above.

**Comment by mispp** [comment]
Ok, great. Thanks.
