### ISSUE TITLE
How to detect no internet?

### ISSUE THREAD

**Issue by Gildedter** [elbywan/wretch#243]
I assumed the `.catch()` would run after my `.res()` call when no internet is present or when it suddenly cuts off due to poor signal strength, but that doesn't seem to be the case.

**Comment by elbywan** [comment]
Hey @Gildedter,

> How to detect no internet? 

From the [fetch docs](https://developer.mozilla.org/en-US/docs/Web/API/Window/fetch#error):

>A  fetch() promise only rejects when the request fails, for example, because of a badly-formed request URL or a network error. A fetch() promise does not reject if the server responds with HTTP status codes that indicate errors (404, 504, etc.). Instead, a then() handler must check the [Response.ok](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok) and/or [Response.status](https://developer.mozilla.org/en-US/docs/Web/API/Response/status) properties.

So you could use [`fetchError()`](https://elbywan.github.io/wretch/api/interfaces/index.WretchResponseChain#fetchError):

<img width="577" alt="Capture d’écran 2024-09-06 à 22 53 58" src="https://github.com/user-attachments/assets/c72301b1-f84b-4d94-9b22-92bba7f6310c">
