### ISSUE TITLE
Basic Auth Addon - Not browser independent

### ISSUE THREAD

**Issue by dmf444** [elbywan/wretch#245]
I'm using this library in an electron project, running node 18, and the following line from the Basic Auth Addon fails because btoa is not available: `btoa(String.fromCharCode(...utf8Bytes))`. Can this be made into a polyfill?

Thanks

**Comment by elbywan** [comment]
Hey @dmf444,

> btoa is not available

This is weird, [`btoa` is part of the nodejs standard library since node@16](https://nodejs.org/api/globals.html#btoadata).
