### ISSUE TITLE
Set .auth() with a function on each requests

### ISSUE THREAD

**Issue by TheSuperFly** [elbywan/wretch#25]
Hello! 

Great work for this little package. I like the way it normalizes behaviors.

I'm currently having a problem with setting the `wretch().auth()` dynamically. Before I'm connecting, I don't have things to put into `wretch().auth()` but when I'm connected, I have a token that I could not bind to `wretch().auth()` because it doesn't run on every requests.

Any idea?

**Comment by elbywan** [comment]
Hey @TheSuperFly

> Great work for this little package. I like the way it normalizes behaviors.

Thanks 😄!

> Any idea?

You could try any of these options:

- Wrap wretch inside a function call 

```js
function authWretch(token) {
   return wretch().auth(token)
}

authWretch(token)...
```

- Use middlewares

```js
const authMiddleware = next => (url, opts) => {
  if(opts.context && opts.context.token) {
    return next(url, {
      ...opts,
    headers: {
      ...opts.headers,
      Authorization: opts.context.token
    }
  })
  }
  return next(url, opts)
}


wretch().middlewares([ authMiddleware ])
```

- Use a brand new feature I added for you in the dev branch 😉:

```js
/* Small fictional example: deferred authentication */

// If you cannot retrieve the auth token while configuring the wretch object you can use .defer to postpone the call
const api = wretch("...").defer((w, url, options)  => {
  // If we are hitting the route /user…
  if(/\/user/.test(url)) {
    const { token } = options.context
    return w.auth(token)
  }
  return w
})

// ... //

const token = await getToken(request.session.user)

// .auth gets called here automatically
api.options({
  context: { token }
}).get().res()
```

**Comment by TheSuperFly** [comment]
Hey Julien, 

Thanks a lot for the quick feedback, you even developed a feature! You are awesome 😄 

I've ended up by doing a middleware to handle it, just like you did but I will refactor it to try out the defer feature you've developed. 

Kudos + I'm closing it as you provided a solution and will let you know here when I will test it.
