### ISSUE TITLE
JUST A QUESTION: Does it work with nextjs ? (server side with additional nextjs features)

### ISSUE THREAD

**Issue by saver711** [elbywan/wretch#252]

**Comment by elbywan** [comment]
Yes

https://github.com/elbywan/wretch/issues?q=is%3Aissue+nextjs+is%3Aclosed

**Comment by saver711** [comment]
> Yes
> 
> https://github.com/elbywan/wretch/issues?q=is%3Aissue+nextjs+is%3Aclosed

@elbywan 
can u provide example shows how to do these
`
fetch(`https://...`, { cache: 'force-cache' | 'no-store' })
fetch(`https://...`, { next: { revalidate: false | 0 | number } })
fetch(`https://...`, { next: { tags: ['collection'] } })
`
