### ISSUE TITLE
Doc: Retry Until example issue

### ISSUE THREAD

**Issue by scottix** [elbywan/wretch#255]
## Summary
Incorrect syntax for retry until example.

## Issue
Small issue with the until syntax. response or error could potentially be undefined.
```
until: (response, error) => response && (response.ok || (response.status >= 400 && response.status < 500))
```
until expects a boolean or Promise<boolean> but response could potentially be undefined in a network error.

## Solution
Short circuit the response to handle when it is undefined
```
until: (response, error) => !!response && (response.ok || (response.status >= 400 && response.status < 500))
```

**Comment by elbywan** [comment]
Hey @scottix, thanks for reporting the issue :bow:!

Just fixed the documentation, several snippets were indeed not passing the type checker.
