### ISSUE TITLE
Polling requests (custom middleware)

### ISSUE THREAD

**Issue by mkramb** [elbywan/wretch#27]
Hi!

Firstly, thanks for a great library - really useful!

I would like to create a custom middleware, which would call the same request again at a later time (as interval - for polling). For example: in options() I would specify needed behavior:

```
return .api
   .url(urlPath)
   .options({
      refetchDelay: 2000,
      refetchUntil: () => this.refetchEnabled
   })
   .get()
   .json(({ data }) => {
      this.applications.set(data);
   });
```

The problem is that a single request should be able to produce multiple requests. Having something like this works that it refetches the request, but the callback (json()) is not being executed (not being resolved):

```
export const refetch: RefetchMiddleware = () => {
    return next => (url, opts) => {
        const refetchRequest = (response: any): any => {
            const refetchDelay = opts.refetchDelay || defaultDelay;
            const refetchUntil = opts.refetchUntil || defaultUntil;

            if (refetchUntil()) {
                return new Promise(resolve => {
                    setTimeout(() => {
                        resolve(next(url, opts).then(refetchRequest));
                    }, refetchDelay);
                }).then(refetchRequest);
            }

            return response;
        };

        return next(url, opts).then(refetchRequest);
    };
};
```

Thoughts?

Thanks,
Mitja

**Comment by mkramb** [comment]
Probably middlewares are not the best approach for polling, but something that manages from outside, e.g.:
```

export function pollingRequest(url: string, callback: (data: any) => void, until: () => boolean, timeout: number) {
    const request = fetchApi.url(url).options({ skipCache: true });
    const polling = () =>
        setTimeout(() => {
            if (until()) {
                request.get().json(callback);
                polling();
            }
        }, timeout);

    return request
        .get()
        .json(callback)
        .then(polling);
}
```

**Comment by elbywan** [comment]
Hi @mkramb!

> Firstly, thanks for a great library - really useful!

Thanks a bunch! 
And sorry for the delayed response, It might be a little bit late but I will try to answer my best.

First, indeed a middleware is not the best approach since it will return a promise that will get resolved only **once**. Hence, if you try to replay it as you noted the resolver chain will not be called.

Wrapping the polling code inside a function is a perfectly valid way to do that 😉, but I can also suggest using the `.resolve` function to achieve the same result with a slightly more expressive syntax :

```js
const pollingResolver = ({ 
    delay = 1000, 
    method = 'get',
    until = () => true,
    resolver
}) => (_, request) => {

    // Chain the resolvers here - not at the bottom
    resolver(_)
    if(!until()) {
        // Replay request
        setTimeout(() => request[method](), delay)
    }
}

let counter = 0

wretch('https://www.google.com')
    .resolve(pollingResolver({
        until: () => { counter++; return counter >= 5 },
        resolver: _ => _.notFound(console.error).text(console.log) 
    }))
    .get()
    // Do not chain anything here! It will only get called for the first request.
```
