### ISSUE TITLE
DELETE method with body

### ISSUE THREAD

**Issue by junkboy0315** [elbywan/wretch#28]
Hi @elbywan, wretch simplifies my code dramatically. thanks a lot.

btw, in some cases, I have to use DELETE method with the body.
For now it seems that sending a body using the DELETE method
on wretch is not allowed.

I guess DELETE with body is not prohivited by the regulation.

so if I write some PRs, could you accept it? does this make sense?

thanks.

**Comment by elbywan** [comment]
> Hi @elbywan, wretch simplifies my code dramatically. thanks a lot.

Hi @junkboy0315, thanks 😄.

> btw, in some cases, I have to use DELETE method with the body.

Did you try using the `.body` or `.json` functions to set the body (https://github.com/elbywan/wretch#body-types) ?

I have no issues on Chrome :

<img width="308" alt="capture d ecran 2018-07-19 a 08 13 10" src="https://user-images.githubusercontent.com/3428394/42924740-d65a6a78-8b2b-11e8-8ffd-c13632b1f65c.png">

<img width="138" alt="capture d ecran 2018-07-19 a 08 13 41" src="https://user-images.githubusercontent.com/3428394/42924747-dff485e6-8b2b-11e8-9732-19901bf6a146.png">

**Comment by junkboy0315** [comment]
My bad... `.json` worked perfectly.
Thank you!
