### ISSUE TITLE
Consider respecting semantic versioning

### ISSUE THREAD

**Issue by limonte** [elbywan/wretch#30]
On the "New Release" page, GitHub suggesting reading about semantic versioning

![image](https://user-images.githubusercontent.com/6059356/43355286-9404dc88-9262-11e8-91e3-4e689bb2fffb.png)

### https://semver.org/

- MAJOR version when you make **incompatible** API changes,
- MINOR version when you add functionality in a **backwards-compatible** manner, and
- PATCH version when you make backwards-compatible bug fixes.

**DO NOT SHIP BREAKING CHANGES IN MINOR RELEASES.** 

Simple as that. 

Don't be afraid of numbers, they are here to help us. Use numbers properly and have a nice day.

**Comment by elbywan** [comment]
@limonte Thanks, I know about semantic versioning. I simply consider that some extremely minor breaking changes do not necessarily always need a major version bump. 😉

**Comment by limonte** [comment]
> minor breaking changes

There's no such thing as "extremely minor breaking change". Things are either breaking or not, like boolean, like 0 or 1 ;)

If it's breaking, bump the major. Your user won't mind that. They will mind if their production accidentally stopped working because of `npm/yarn update`.

**Comment by elbywan** [comment]
> If it's breaking, bump the major. Your user won't mind that. They will mind if their production accidentally stopped working because of npm/yarn update.

Yeah to be fair you're right, I was not even convinced by my own arguments ;).

So I'll stick to the semver for next releases! 👍

**Comment by limonte** [comment]
Lovely! Now I'm considering using `wretch` in my project :)
