### ISSUE TITLE
Improve `.query()` function to handle edge cases

### ISSUE THREAD

**Issue by tychota** [elbywan/wretch#33]
# Intro

On my actual project, I use wretch. 

Don't get me wrong, wretch is awesome: it is one of the best designed fetch wrapper I have seen so far and I have been using so far and I've been using a few (XMLHTTPRequest direct, axios, request, superagent, fetch directly, frisbee and now wretch).

Before everything, thank you. 😍

# Problem I try to solve

`.query()` is misleading. It try to handle stringification / url encoding of javascript object and manage to do it well for 80% of the cases (common one) but fails the complex one.

On my project for instance we have done:

```ts
wretch("https://example.com/test").query({ pagination: { pageSize: 25, page: 1 }}).get()
```

which outputed : `https://example.com/test?pagination[object Object]` 😱

That cause us a bug and took a while to debug (2h or so).

I plan to improve wretch so users does not have to be wretch finding bugs.

# Reference implementation

For me the reference implementation is https://github.com/ljharb/qs and looking at https://github.com/ljharb/qs/blob/master/test/stringify.js it supports the following features (checkbox checked if wretch support it right now)

- [x] stringify a string is indempotent `a=b`-> `a=b`
- [x] stringify not html feature like `{ a: '€' }`  -> `'a=%E2%82%AC'`
- [x] stringify object with space in key or value `{ 'a a': 'b 'b'}` -> `'a+a=b+b'`
- [ ] stringify nested object like `{ a: { b: 'c' } }` -> `'a%5Bb%5D=c'`
- [ ] stringify nested object with dot notation `{ a: { b: 'c' }` -> `'a.b=c'`
- [ ] stringify array value with indice notation `{ a: ['b', 'c']}` -> `'a[0]=b&a[1]=c'`
- [x] stringify array value with repeat notation `{ a: ['b', 'c']}` -> `'a=b&a=c'`
- [ ] stringify array value with bracket notation `{ a: ['b', 'c']}` -> `'a[]=b&a[]=c'`
- [ ] stringify object skipping null/undefined value `{ a: 'b', c: null}` -> `'a=b`
- [ ] stringify date using toIsoDate
- [ ] ...

# Next steps

If it is ok for you:

- [x] I will create a PR that will add failing tests https://github.com/elbywan/wretch/pull/34
- [ ] you will determine what case you want to support in wretch (do we intend 100% compatibility with internet standards, if not how do we plan to let the user "hook" encoders to support proper encoding)
- [ ] depending on that decision, we decide to code the missing part or rely on https://github.com/ljharb/qs
- [ ] I code the missing part, with your help and review

# Note 

I'm support use to contributing to repo with prettier activated. Here I needed to deactivate it then do the formatting by hand which is painful now that I get use to format.

Would you mind an other PR to include prettier  and configure it to be the less different to actual source code ?

**Comment by tychota** [comment]
There is some open question about design potential breaking changes.

Query is now:

```ts
query(qp: object | string, replace: boolean)
```

where i think:

```
query(qp: object | string, options: WretchQueryOptions)

interface WretchQueryOptions {
  replace: boolean; // default false
  encode: boolean; // default false
  nestedObjectFormat: "bracket" | "dot"; // default bracket
  arrayFormat: "repeat" | "indices" | "bracket"; // default arrayFormat 
}
```
will be more suitable since we can more options as edge cases goes.

This might be breaking changes (even if we can check if the seconf params of query is boolean and prevent breaking changes by handling it correctly).
What is your policy about breaking changes ?

**Comment by elbywan** [comment]
Hey @tychota !

> Don't get me wrong, wretch is awesome: it is one of the best designed fetch wrapper I have seen so far and I have been using so far and I've been using a few (XMLHTTPRequest direct, axios, request, superagent, fetch directly, frisbee and now wretch).

Thanks a bunch, it's **great** to read that ❤️ 👍 !

> .query() is misleading. It try to handle stringification / url encoding of javascript object and manage to do it well for 80% of the cases (common one) but fails the complex one.

Actually handling 80% of the cases is exactly what I wrote `.query()` for 😉. It has never been supposed to handle all the cases, especially since there is no real convention about how to serialize objects and arrays into query strings (for instance arrays are handled in a different way depending on which backend server you use).

But I understand what you mean about the fact that for complex use cases it is *misleading*, I will **definitely** highlight that in the documentation :memo:.

> For me the reference implementation is https://github.com/ljharb/qs and looking at https://github.com/ljharb/qs/blob/master/test/stringify.js it supports the following features (checkbox checked if wretch support it right now)

On the other hand, I am not super convinced that re-coding `qs` features inside `wretch` would actually be beneficial, because:

- One of the main advantages of `wretch` compared to other libraries is its small bundle size. Adding these features would bloat the lib.
- `qs` is already great at encoding query strings.
- `Wretch` is already compatible with `qs`, both can be used together without any pain!

#### Wretch + qs

[-> On runkit](https://runkit.com/elbywan/5b7fa9951ba3930012db1e9c)

```js
const wretch = require("wretch")
const qs = require("qs")

const baseWretch = wretch("https://duckduckgo.com/")
const qsQuery = { pagination: { pageSize: 25, page: 1 }}

// 1st way - Call .qs inside .query //

console.log('1 > ' + baseWretch.query(qs.stringify(qsQuery))._url)

// "1 > https://duckduckgo.com/?pagination%5BpageSize%5D=25&pagination%5Bpage%5D=1"

// 2nd way - Use .defer (preferred way) //

const qsWretch = baseWretch.defer((w, url, { qsQuery, qsOptions }) => (
    qsQuery ?
        w.query(qs.stringify(qsQuery, qsOptions)) :
        w
))
qsWretch.options({ qsQuery }).get().res(res => {
    console.log('2 > ' + res.url)
   // "2 > https://duckduckgo.com/?pagination%5BpageSize%5D=25&pagination%5Bpage%5D=1"
}).catch(console.error)

// 3rd way - Desperate monkey patching ;) //

function appendQueryParams(url, qp, replace) {
    let queryString

    if(typeof qp === "string") {
        queryString = qp
    } else {
        queryString = qs.stringify(qp)
    }

    const split = url.split("?")
    if(replace || split.length < 2)
        return split[0] + "?" + queryString

    return url + "&" + queryString
}
wretch().__proto__.query = function (qp, replace) {
    return this.selfFactory({ url: appendQueryParams(this._url, qp, replace) })
}
console.log('3 > ' + baseWretch.query(qs.stringify(qsQuery))._url)
// "3 > https://duckduckgo.com/?pagination%5BpageSize%5D=25&pagination%5Bpage%5D=1"
```


> I'm support use to contributing to repo with prettier activated. Here I needed to deactivate it then do the formatting by hand which is painful now that I get use to format.

Wretch is already using `eslint`. There is an `npm run fix` script which runs `eslint --fix` under the hood. That will format the code the same way as prettier (but with other rules 😉).

**Comment by elbywan** [comment]
Updated the doc : https://github.com/elbywan/wretch#queryqp-object--string-replace-boolean

**Comment by tychota** [comment]
> Thanks a bunch, it's great to read that ❤️ 👍 !

Thank for your fast, clear and detailed answer as always. 
It is really nice to have reactive maintenairs, caring to explain their decisions.

I must admit I work on React Native project right now, not PWA, so I didn't think about the size. I looked the size of qs gzipped and according to https://bundlephobia.com/result?p=qs@6.5.2, it will double the size.

> Actually handling 80% of the cases is exactly what I wrote .query() for 😉. It has never been supposed to handle all the cases, especially since there is no real convention about how to serialize objects and arrays into query strings (for instance arrays are handled in a different way depending on which backend server you use).

Not fully aligned on this, I must say!

I agree that:
- it is ok to not support some configuration (aka support one way of encoding objects, onee way of encoding array, ect)

I don't agree with some points and I think:
- it isn't explicit right now and it should be. Rather than encoding `{'a':{'b':'c'}}` to `a=[object Object]`, wretch should detect that the `{'b':'c'}` ist not string, number, boolean or array and thus skip it and print an error.
- there is some topics that are ok to implement based on the principe user may never want the current state and that implementing it its not that costy in bundle size and complexity. E.g.:
  - skipping null values (right now it display `test=null`)
  - not encoding prototype property (if the the user encode a sequelize object, it is nice to have not the full sequelize prototype)

> On the other hand, I am not super convinced that re-coding qs features inside wretch would actually be beneficial, because:
> 
> - One of the main advantages of wretch compared to other libraries is its small bundle size. Adding these features would bloat the lib.
> - qs is already great at encoding query strings.
> - Wretch is already compatible with qs, both can be used together without any pain!

Ty for the great alternatives.

For longer term i will prefer the solution 2.b:

```ts
import { encodeQueryString } from 'wretch-middlewares';

const myWretch = wretch("https://duckduckgo.com/").middlewares([encodeQueryString({
  nestedObjectFormat: "bracket",
  arrayFormat: "repeat",
})]);

myWretch().query({'a': ['b', 'c', Date.now()]});
```

Is it possible now to use middleware (assuming I created the middleware before) like this ?

If yes can, can you help me to implement it !

> Wretch is already using eslint. There is an npm run fix script which runs eslint --fix under the hood. That will format the code the same way as prettier (but with a different ruleset 😉).

Nice to know. I still think prettier and eslint have differents goal and not mutually exclusive.
But that another discussion, happy to have it later in an other.

> Updated the doc : https://github.com/elbywan/wretch#queryqp-object--string-replace-boolean

Nice.

I will also include something in the title warning the user that "edges cases (query encoding complexe data structure, retry) are not included by default but can be easily plug and play with middlewares".

![image](https://user-images.githubusercontent.com/13785185/44577945-9dd75980-a792-11e8-9f69-890a1af7717d.png)

**Comment by elbywan** [comment]
> wretch isn't explicit right now and I think, it should be. Rather than encoding {'a':{'b':'c'}} to a=[object Object], wretch should detect that the {'b':'c'} ist not string, number, boolean or array and thus skip it and print an error (console.error or warn)

I don't think so, because the object could for instance have an overloaded `toString` method that would serialize and encode it. It's not *invalid*.

> Is it possible now to use middleware (assuming I created the middleware before) like this ?
If yes can, can you help me to implement it !

Sure! I would start with something like this:

```js
// Untested

import qs from 'qs'

const qsMiddleware = (qsOptions = {}) => next => (url, options) => {
    const { queryString } = options
    if(queryString) {
        return next(url + qs.stringify(queryString, qsOptions), options)
    }
    return next(url, options)
}
```

Then use it like this:

```js
const myWretch = wretch("https://duckduckgo.com/").middlewares([
  qsMiddleware({
    // any qs.stringify options here
  })
]);

myWretch().options({ queryString: {'a': ['b', 'c', Date.now()]}})
```

*Note that you cannot modify the `.query` function behaviour by using a middleware.*

Middlewares are not meant to do that, but using `.options` is not really different it's only slightly more verbose.
