### ISSUE TITLE
Resolving an original request

### ISSUE THREAD

**Issue by sarneeh** [elbywan/wretch#36]
I'd like to decorate the `response` object with some custom data after an original request retry resolves. Something like this:

```js
const refreshAndRetry = async (error, originalRequest) => {
  const token = await wretch()
    .url('/auth/refresh')
    .get()
    .json();

  return originalRequest
    .resolve(resolver =>
      resolver.res(response => {
        response.token = token;
        return response;
      })
    )
    .auth(`Bearer ${token}`)
    .get()
    .unauthorized(error => {
      throw error;
    })
    .json();
};
```

As you can see - I'd like to have a `response.token` property on a request which had to refresh the token and retry. I need this to handle fresh tokens somewhere in the higher level of the application.

Unfortunately the above code throws a `originalRequest.resolve(...).auth(...).get(...).unauthorized is not a function` error.

Could you please help and tell me what I'm doing wrong and how can I solve this?

**Comment by elbywan** [comment]
> Could you please help and tell me what I'm doing wrong and how can I solve this?

Well for the actual error comes from the fact that in your example above you have the following code:

```js
originalRequest
    .resolve(resolver =>
      resolver.res(response => {
        response.token = token;
        return response;
      })
    )
    .auth(`Bearer ${token}`)
    .get()
    .unauthorized(error => {
      throw error;
    })
    .json();
```

Which gets resolved into:

```js
originalRequest
    .auth(`Bearer ${token}`)
    .get()
     // <- resolvers are injected here
    .res(response => {
        response.token = token;
        return response;
      })
    .unauthorized(error => {
      throw error;
    })
    .json();
```

But chaining `res().unauthorized().json()` is impossible because `.res` returns a Promise<Response>, at this point the only callable functions are `.then` `.catch` and `.finally`.

-------

> I'd like to decorate the response object with some custom data after an original request retry resolves. 

Now if you want to decorate the raw response you could do it without using a resolver:

```js
originalRequest
    .resolve(resolver =>
      resolver.res(response => {
        response.token = token;
        return response;
      })
    )
    .auth(`Bearer ${token}`)
    .get()
    .unauthorized(error => {
      throw error;
    })
    .res(response => {
        response.token = token
        return response
    })
```

But if you do that, then when the request will be replayed the `Response` object will be returned instead of the parsed body. Which could lead to some unexpected surprises 😉.

I made a small example on RunKit if you want to experiment a bit: https://runkit.com/embed/rq4fgrkzdelb

**Comment by sarneeh** [comment]
Oh, well, that makes sense 😄 It's bad that the only way to get the replayed response is by using `.then()`. It's kinda confusing. It would be great if I'd could do something like this:

```js
const replayOn405 = wretch()
    .catcher(401, async (error, originalRequest) => {
        const token = await refreshToken();
        return originalRequest
            .auth(`Bearer ${token}`)
            .retry()
            .error(405, err => { throw err })
    })
```

And that it would be completely transparent to the caller. What do you think about this idea?

**Comment by MarlBurroW** [comment]
@sarneeh  I just wrote a [VERY similar idea](https://github.com/elbywan/wretch/issues/35#issuecomment-464150047) just before seeing your comment. I think this is a good idea, but not sure about the feasibility.

**Comment by elbywan** [comment]
@sarneeh @MarlBurroW Actually, I think the proper way of doing this is to use a `middleware`.
Using a `resolver`/`catcher` to return an alternative fetch Response is really tricky because of the way `Promises` work.

I drafted a small middleware example (and a real use case for the openWeatherMap api) on [runkit](https://runkit.com/elbywan/5c7193ba6ce50d0013dca83f) that should help alleviate the problem.

I recommend reading the code there, but here is what the middleware part looks like:

```js
// Re-auth middleware
const reauthMiddleware = ({
    // Default values
    authOn = response => response.status === 401,
    setToken = (token, { url, options }) => ({
        url,
        options: {
            ...options,
            headers: {
                ...(options.headers || {}),
                ...{ Authorization: 'Bearer ' + token }
            }
        }
    }),
    // This one is always needed
    renewToken
}) => next => async (url, opts) => {
    // Perform the request
    const response = await next(url, opts)
    // If reauth is not needed, return the response right away
    if(! await Promise.resolve(authOn(response))) {
        return response
    }
    // If reauth is needed, renew the token
    const token = await renewToken(url, opts)
    // Mutate options based on the token
    const args = setToken(token, { url, options: opts })
    // Perform the request again with the updated options
    return next(args.url, args.options)
}
```

**Comment by elbywan** [comment]
@sarneeh Just realized that I forgot to address the original issue.

> As you can see - I'd like to have a `response.token` property on a request which had to refresh the token and retry. I need this to handle fresh tokens somewhere in the higher level of the application.

If you want to store a variable for later consumption, you could do the following:

```js
// In the above middleware
const token = await renewToken(url, opts)
// Add these two lines
if(options.context)
    options.context.token = token
// ...
```

```js
// When performing the actual request
const context = {}
const response = await wretch(....).object({ context })...
// The middleware updated the context object using its reference
console.log(context.token)
```

**Comment by sarneeh** [comment]
@elbywan That's cool that it's possible to solve the issue, but I was thinking more about some clear API for that. There's almost nothing about a thing like `context` in the docs, so I'd probably never came up with an idea like that without looking into the library - and I guess it's not what we want the users to do, right? I think we'd like a clear and readable API :smiley:

**Comment by elbywan** [comment]
I added a [paragraph to the README](https://github.com/elbywan/wretch#context) that highlights how to add a context for middlewares.

Regarding a dedicated  API for that, basically the context thing is just:

- Creating an object
- Passing the object by reference
- Mutating the reference

I could add a new `.context()` method that would return a freshly created object (`const [ w, context ] = wretch().context()`), but I really feel like these concepts are baked into the language itself.
Plus it would break the chain by returning a pair.

So hopefully the documentation should be enough 👍.
