### ISSUE TITLE
How to handle 204 responses ?

### ISSUE THREAD

**Issue by Aarbel** [elbywan/wretch#38]
I've got this error with wretch and 204 response with no json in the response. How could i fix it ? Thanks a lot ! 

`SyntaxError: Unexpected end of JSON input at eval`

![image](https://user-images.githubusercontent.com/25119847/48662158-3aea1b80-ea7e-11e8-9cb7-2bc9bce23d23.png)

My code : 
```
wretch()
	.url('/toto/65465874')
	.options({ credentials: 'include' })
	.delete()
	.json();
```

**Comment by elbywan** [comment]
Hey @Aarbel,

If your 204 response does not contain a body, then calling `.json()` is indeed expected to throw.

You can try using `.res()` to retrieve the raw fetch response instead:
 ```js
wretch()
	.url('/toto/65465874')
	.options({ credentials: 'include' })
	.delete()
	.res(); // <--
```

**Comment by Aarbel** [comment]
Yes i just remove the .json() part and that works ! Thanks a lot for your help !
