### ISSUE TITLE
res() usage question

### ISSUE THREAD

**Issue by mvasin** [elbywan/wretch#40]
I've noticed the readme uses `res()` in a few places, without using the response (I mean `.res(response => do something here with response)`). Here's one example: 
```
wretch().url("...").get().json(/* ... */)

// Can be used to set a base url

// Subsequent requests made using the 'blogs' object will be prefixed with "http://mywebsite.org/api/blogs"
const blogs = wretch("http://mywebsite.org/api/blogs")

// Perfect for CRUD apis
const id = await blogs.post({ name: "my blog" }).json(_ => _.id)
const blog = await blogs.url(`/${id}`).get().json()
console.log(blog.name)

await blogs.url(`/${id}`).delete().res()

// And to replace the base url if needed :
const noMoreBlogs = blogs.url("http://mywebsite.org/", true)
```

I'd like to understand what `res()` does at the end of ```await blogs.url(`/${id}`).delete().res()```.

**Comment by elbywan** [comment]
Hi @mvasin,

> I'd like to understand what res() does at the end of await blogs.url(`/${id}`).delete().res()

The return type of `.res()` is a `Promise`, unlike `.delete()` that returns a custom object. In this particular example, I call `.res()` in order to be able to `await` it.

**Comment by mvasin** [comment]
But then why do the docs say `res()` can return `any`?
```
res(cb: (response : Response) => any)
```
Seems like it's out of sync with [code](https://github.com/elbywan/wretch/blob/master/src/resolver.ts#L12).

**Comment by elbywan** [comment]
> But then why do the docs say res() can return any

No, it means that the **callback** you provide can return anything, which is I think correct:
```js
const anything = await wretch().get().res(res => 'return anything…')
```

**Comment by mvasin** [comment]
Oh yes, I see.

Don't you think it will be very useful to specify in the docs return types for all the methods, to make it crystal clear which methods return a promise and which return a chained wrecher instance?

**Comment by elbywan** [comment]
> Don't you think it will be very useful to specify in the docs return types for all the methods, to make it crystal clear which methods return a promise and which return a chained wretch instance?

Yes, good point 😉. I'll add more details in the documentation.

**Comment by elbywan** [comment]
Just added the return types for the methods + a small paragraph with an example.
