### ISSUE TITLE
Clarification re: try/catch, and .catch method

### ISSUE THREAD

**Issue by mikefowler** [elbywan/wretch#43]
I will preface by saying: @elbywan thanks your work on this project. It has made working with fetch so much more palatable, and the usability of this abstraction is wonderful.

I have some code that looks like this:

```ts
async function refresh() {
  const accessToken = getAccessToken();

  try {
    await wretch(`path/to/oauth/refresh`)
      .options({
        credentials: 'include',
      })
      .auth(`Bearer ${accessToken}`)
      .get()
      .catch((e) => {
        // this is never called
        debugger;
      });
  } catch (e) {
    // this is also never called
    debugger;
  }

  debugger;
}
```

I'm testing a flow where a user's refresh token is absent or invalid, and so I expect this refresh endpoint to fail with a 400. When I call `refresh()`, it seems that the third debugger statement is encountered _first_, and what is more, the Promise returned by Wretch hasn't even returned yet. In fact, the two other debugger statements are never even encountered, even when the request returns as a 400.

I must be missing something about the control flow of Wretch. Does anything stick out?

**Comment by elbywan** [comment]
Hey @mikefowler,

> I will preface by saying: @elbywan thanks your work on this project. It has made working with fetch so much more palatable, and the usability of this abstraction is wonderful.

Thank you very much! 😄

> I must be missing something about the control flow of Wretch. Does anything stick out?

I think that your `wretch` chain is missing a [response type](https://github.com/elbywan/wretch#response-types). Could you try adding `.res` (for instance) at the end of the chain?

```js
await wretch(`path/to/oauth/refresh`)
      .options({
        credentials: 'include',
      })
      .auth(`Bearer ${accessToken}`)
      .get()
      .res() // <- here
```

This should do the trick!

**Comment by mikefowler** [comment]
@elbywan that did it! Thanks for the prompt response!
