### ISSUE TITLE
Weird sefFactory defaults behavior 

### ISSUE THREAD

**Issue by mrazorvin** [elbywan/wretch#44]
This part of code 

    private selfFactory({ url = this._url, options = this._options, catchers = this._catchers,
                resolvers = this._resolvers, middlewares = this._middlewares, deferredChain = this._deferredChain } = {}) {
        return new Wretcher(url, options, catchers, resolvers, middlewares, deferredChain)
    }

cause new wretches instance use its parent middlewares, resolvers ... this optimization cause weird issue with following part

        /**
         * Catches an http response with a specific error code or name and performs a callback.
         */
        error(errorId, cb) {
            catchers.set(errorId, cb)
            return responseChain
        },

which cause parent object to use error handlers from new wretches instances

for example

  /**
   * Change 404 error handler
   */
  handleNotFound(): Api<"404-undefined"> {
    return this.merge({
      api1Endpoint: this.ap1Endpoint.resolve((request) => request.notFound(() => undefined)),
      api2Endpoint:  this.ap2Endpoint.resolve((request) => request.notFound(() => undefined)),
    }) as Api<"404-undefined">;
  }

Mutate original  this.ap1Endpoint and it start use error handler from new instance

This code fix problem

this.ap1Endpoint.catcher(404, (() => undefined)),

but you can get rid of all such problems if selfFactory won't use objects from parent, instead it could do a shallow copy of all required properties

**Comment by elbywan** [comment]
Hi @mrazorvin, thanks a lot for reporting the issue! 👍 

I just released wretch `1.5.1` that contains a fix.
