### ISSUE TITLE
handling error before .[response type]()

### ISSUE THREAD

**Issue by neves** [elbywan/wretch#45]
First of all, awesome API!

this works `wretch().get().error()` but not this `wretch().error().get()` gives `.error is not a function`.

How can I setup a default error handler, before calling get/post/etc?

**Comment by elbywan** [comment]
> First of all, awesome API!

Hi @neves, thanks a lot 😄!

> How can I setup a default error handler, before calling get/post/etc?

To do that, you can use the [catcher](https://github.com/elbywan/wretch#catchererrorid-number--string-catcher-error-wretchererror-originalrequest-wretcher--void) method.

```js
const w = wretch()
  .catcher(404, err => redirect("/routes/notfound", err.message))
  .catcher(500, err => flashMessage("internal.server.error"))

w.url(...).get() // 404 and 500 are already taken care of
```

**Comment by neves** [comment]
Is there a good reason I can't use `.error` and others syntactic sugar like `.badRequest`?

**Comment by elbywan** [comment]
> Is there a good reason I can't use .error and others syntactic sugar like .badRequest?

Well these helpers (`notFound`, `badRequest`…) are meant to be used after the request resolves. 
`catcher` on the other hand is meant to be used before the request has been sent. 

Using the helpers before the request has been sent will just not work and throw an error.

**Comment by neves** [comment]
Maybe the docs need to be updated at https://github.com/elbywan/wretch#catchers
or even better, add those syntactic sugar to be used before request

**Comment by elbywan** [comment]
I find it confusing to duplicate method names (catcher is "borderline" already since it is used at 2 places). 
And I don't want to bloat the library by adding too much extra stuff.

Also, I already linked the proper section of the documentation: 

https://github.com/elbywan/wretch#catchererrorid-number--string-catcher-error-wretchererror-originalrequest-wretcher--void

**Comment by neves** [comment]
Are you sure? This code does not work:

> // Default catchers can be overridden if needed.
> w.url("...").notFound(err => /* overrides the default 'redirect' catcher */)

**Comment by elbywan** [comment]
> This code does not work

Indeed this line has a typo thanks for pointing this out 👍 (just pushed a fix).

**Comment by tmartensen** [comment]
@elbywan Can this fix be published?
