### ISSUE TITLE
res() value after error

### ISSUE THREAD

**Issue by eladrof** [elbywan/wretch#46]
Hi

Is there a way to enable an error to be passed to a response handler? for example have the res() object status equal to the error code?

In any case, thanks for this amazing library!

**Comment by elbywan** [comment]
Hey @eladrof,

> Is there a way to enable an error to be passed to a response handler? for example have the res() object status equal to the error code?

No I don't think you can since getting an error "jumps" the execution forward past the handlers. But the other way around is totally possible: (res() object inside the error handler)

```js
const result = await wretch('https://google.com/toto')
    .get()
    .notFound(error => { 
        // error.response contains the server response object.
        return error.response.status 
    })
    .res()
    
// Prints 404
console.log('result: ' + result)
```

> thanks for this amazing library!

Thanks! 🙇

**Comment by eladrof** [comment]
@elbywan, 
This is what I was looking for, thanks!

Appreciate your help
