### ISSUE TITLE
Timeout timers should be cleared when requests are finished

### ISSUE THREAD

**Issue by stanmots** [elbywan/wretch#50]
Hi, thanks for this great library. 

I don't know whether this should be considered as a bug,  but I see that timeout timers are not cleared even if the request promise has been resolved or rejected. Here is the [relevant code line](https://github.com/elbywan/wretch/blob/master/src/resolver.ts#L124). 

If you need an idea of how this can be fixed look at the following [axios code snippet](https://github.com/axios/axios/blob/21ae22dbd3ae3d3a55d9efd4eead3dd7fb6d8e6e/lib/adapters/http.js#L23).

I think it's important to clear timers so that resources are not wasted without any purpose. As far as I can see, to implement this feature we need to call `clearTimeout` in the following cases:

- Promise resolved
- Promise rejected
- AbortController called `abort`

**Comment by elbywan** [comment]
Hi @stanmots,

> Hi, thanks for this great library.

Thanks 😄.

> I don't know whether this should be considered as a bug, but I see that timeout timers are not cleared even if the request promise has been resolved or rejected

It's a bug indeed, I just released a new version with the fix. Thanks for pointing this out! 👍

**Comment by stanmots** [comment]
Thanks for the quick fix 👍
