### ISSUE TITLE
Broken example in docs

### ISSUE THREAD

**Issue by rebolyte** [elbywan/wretch#51]
The `reAuthOn401` example in the readme is just what I was looking for, but I had to adjust it a little to work correctly. The original:
```js
const reAuthOn401 = wretch()
  .catcher(401, async (error, request) => {
    const token = await wretch("/renewtoken").get().text()
    storeToken(token)
    // The return of `.replay()` is just a vanilla Promise, which has no `.unauthorized()` method
    return request.auth(token).replay().unauthorized(err => { throw err }).json()
  })
```

Updated:

```js
const reAuthOn401 = wretch()
  .catcher(401, async (error, request) => {
    const token = await wretch("/renewtoken").get().text()
    storeToken(token)
    return request
      .auth(token)
      .catcher(401, (errInner, reqInner) => {
        throw errInner;
      })
      .replay()
      .then(resp => resp.json());
  })
```

Unless I'm missing something?

Also, thanks for making the fetch library I always wanted!

**Comment by elbywan** [comment]
Hello @rebolyte!

> thanks for making the fetch library I always wanted!

Thanks a bunch 😄!

> // The return of `.replay()` is just a vanilla Promise, which has no `.unauthorized()` method

About the  documentation example, I tried to reproduce your issue but I could not observe the same behaviour.

According to this [runkit snippet](https://runkit.com/elbywan/5d07ee2fba75b7001aaaa912) `replay()` seems to be returning a `Resolver` object that contains the `unauthorized` method amongst other things.

Out of curiosity, are you using `.resolve()`? It could explain why a vanilla `Promise` gets returned, if the resolver kicks in and resolves the response by calling `.json()` automatically.

**Comment by rebolyte** [comment]
Aha, I am indeed using `.resolve()`. If I need both a `.resolve()` and a `.catcher()`, is my solution above the best way to handle this?

**Comment by elbywan** [comment]
> Aha, I am indeed using .resolve().

😉 

> If I need both a .resolve() and a .catcher(), is my solution above the best way to handle this?

Yes that is a perfectly fine way to handle it!

**Comment by rebolyte** [comment]
Great. Thanks for the quick response!
