### ISSUE TITLE
Wretch does not throw on network errors

### ISSUE THREAD

**Issue by PierBover** [elbywan/wretch#56]
I'm working on a mobile hybrid app. When the user is offline and the request fails fetch does not throw an error but neither does wretch. What happens is that the response is considered ok and it obviously can't be json parsed.

When using fetch it's common to use the `response.ok` flag to prevent this but from what I've seen this is not available in wretch.

What is the appropriate solution to this with wretch?

Should wretch throw an error when the ok flag is false?

Is there a way I can access the native fetch response?

**Comment by elbywan** [comment]
Hi @PierBover,

I'm not familiar with hybrid mobile apps, but it seems that wretch does throw when `response.ok` is false : https://github.com/elbywan/wretch/blob/master/src/resolver.ts#L62

**Comment by PierBover** [comment]
Thanks for the fast response @elbywan .

Not sure what the problem really is but this does not throw when there is network error and breaks when trying to parse to json. It's easy to reproduce. Open your web app and turn off your wifi.

```
try {
	const response = await externalApi.url(endpoint).post(data);
	return response.json();
} catch (error) {
	console.log('POST ERROR', error);
	throw error;
}
```

I've had to resort to doing this to be able to catch those errors...

```
try {
	const response = await externalApi.url(endpoint).post(data);
	try {
		const json = await response.json();
		return json;
	} catch (error) {
		throw 'Network error';
	}
} catch (error) {
	throw error;
}
```

**Comment by elbywan** [comment]
Instead of:

`await externalApi.url(endpoint).post(data);`

Can you try:

`await externalApi.url(endpoint).post(data).json();`

Without the `json()` you are not awaiting a Promise.

**Comment by elbywan** [comment]
Also, to get the native response you can use .res() instead of .json()

**Comment by PierBover** [comment]
> Without the json() you are not awaiting a Promise.

Oh I thought `.post()` was returning a promise.

> Also, to get the native response you can use .res() instead of .json()

I didn't know that either. I skimmed your docs quickly but missed it.

Thanks for your help.
