### ISSUE TITLE
Retrying request, but wait until the user click on a button

### ISSUE THREAD

**Issue by gusmega** [elbywan/wretch#57]
Hi @elbywan, I have a similar use case like #16 but instead of retrying automatically I want to wait for the user to press a button before running the next request. 
I try to use the replay() method as in the docs `originalRequest.replay()` but it does not have the same resolver as the original one;
Can you show me how to achieve this?

**Comment by elbywan** [comment]
Hi @gusmega,

I'm not sure that using `replay()` is the right solution here. This method has been added to the api for very specific purposes.

If you need a user action to retry the request, why not simply create a function that you call on button click and that will perform the same request?
