### ISSUE TITLE
Can't return falsy value from response handler callback

### ISSUE THREAD

**Issue by itsgoingd** [elbywan/wretch#58]
Hey,

From the documentation:

```js
wretch("...").get().json(() => "Hello world!").then(console.log) // Hello world!
```

This does not work if the returned value is `false` or `null` (probably any falsy value), the original request is passed on to the next promise instead.

I took a quick look at the source and I believe it's caused by how the callback is run here 

https://github.com/elbywan/wretch/blob/master/src/resolver.ts#L89-L92

I'm not sure if it's an intentional choice, so when the callback does not return you won't lose the original request, or a bug. Even if it's intentional it might be better to explicitly check if the return value is `undefined` as returning some kind of "success" boolean might be a common use case.

Fortunately the workaround is pretty straight-forward:

```js
wretch("...").get().json().then(() => false).then(console.log)
```

Thanks for this very nice library btw!

**Comment by elbywan** [comment]
Just released v1.5.5 with the fix. 📦
