### ISSUE TITLE
Don't send referrer header

### ISSUE THREAD

**Issue by onel** [elbywan/wretch#59]
Hey, I really the lib but I think I found a strange behavior.
I would like to avoid sending the `Referrer` header but it doesn't seem to work as expected.
My instance is like this:
```
var apiRoot = wretch(root)
  .options({credentials: "include", mode: "cors", referrer: 'no-referrer'})
  .content("application/json")
  .accept("application/json")
```

And when I do `apiRoot.get().json()`, the `Referrer` header is set to `Referer: http://localhost:8080/apps/no-referrer`
I also tried with `false` and `null`, but the string version is added to the root url.
Am I doing something wrong? I know `fetch` accepts that option.

Thanks

**Comment by elbywan** [comment]
Hi @onel,

I had a quick look at the [mdn docs](https://developer.mozilla.org/en-US/docs/Web/API/Request/referrerPolicy), it seems that the correct property is `'referrerPolicy'`, not `referrer`. Can you try with this spelling?

**Comment by onel** [comment]
Ughh, yes. You're absolutely right @elbywan 
Not sure how I missed that. Thanks for the help.
It does work when using `referrerPolicy`
