### ISSUE TITLE
Why do we have to pass AbortController instead of AbortSignal?

### ISSUE THREAD

**Issue by piotr-oles** [elbywan/wretch#60]
Hi!
I very like this library, I was missing such a wrapper over `fetch` 👍 
The problem that I have is that currently using fetch, I developed my `services` to optionally accept `AbortSignal` as a parameter to control cancellation from the outside. This library doesn't accept `AbortSignal` but `AbortController` - by doing this is not compatible with `fetch` implementation. 

Is there a reason why you implemented it that way? 

The fragment that is responsible for that is:
```typescript
    /**
     * Associates a custom signal with the request.
     * @param controller : An AbortController
     */
    signal(controller: AbortController) {
        return this.selfFactory({ options: { ...this._options, signal: controller.signal }})
    }
```
My suggestion is to change it to:
```typescript
    /**
     * Associates a custom signal with the request.
     * @param signal : An AbortSignal
     */
    signal(signal: AbortSignal) {
        return this.selfFactory({ options: { ...this._options, signal }})
    }
```
Unfortunately it would introduce a breaking change. What do you think about it? 😃

**Comment by elbywan** [comment]
Hi @piotr-oles,

> Is there a reason why you implemented it that way?

Well yeah the method name is definitely confusing 😉. `.controller` is used to return the abort controller that wretch generates when none is passed, so I picked `.signal` to pass a controller as it was loosely related in the spec.

Looking backwards it was not the best choice, I'll consider renaming both functions. But I'd like not to break the existing one, so it's unlikely that I'll change `.signal`.

In the meantime, using `wretch.options({ signal })` to pass a custom signal should work.

**Comment by piotr-oles** [comment]
Ok, I got it, thanks :) Would be nice to add in the documentation information that we can use wretch.options({ signal }) instead of .signal({ signal }) :)
