### ISSUE TITLE
How to throw custom errors using the error() handler without trigger the final catch.

### ISSUE THREAD

**Issue by MarlBurroW** [elbywan/wretch#61]
Hi,
I would like to throw some custom errors on some specific http response codes (eg: 422 here), but I also need to throw a more generic error for all other status codes. So I tried something like this:

```javascript
// a very simplified version of my client API layer
wretch("anything")
  .errorType('json')  
  .post(somedata)
  .error(422, error => {throw new ServerValidationError(error)}
  .res(response => /* ... */)
  .catch(error => {
      throw HttpError(error)
   })
```
But throwing a 422 error reject the promise and trigger the `catch` callback at the end (that is the usual behavior on a promise based lib), but then, I got a `HttpError` instead of a `ServerValidationError` when I `.catch()` error on top of my api service.

I was inspired by this example in the documentations:

```javascript
wretch("anything")
  .get()
  .notFound(error => { /* ... */ })
  .unauthorized(error => { /* ... */ })
  .error(418, error => { /* ... */ })
  .res(response => /* ... */)
  .catch(error => { /* uncaught errors */ })
````
For me, this example means 
> If response status code is 418, perform the attached callback, but do not fire the catch(). catch() is only for errors that are not handled by the  `error()` or named errors handlers

But it's probably a misunderstanding of this example, so I changed my code to something like this.

```javascript
wretch("anything")
  .errorType('json')  
  .post(somedata)
  .res(response => /* ... */)
  .catch(error => {
    if (error.response) {
      switch (error.response.status) {
        case 422:
          throw new ServerValidationError(error)
          break
        default:
          throw new HttpError(error)
          break
     }
    } else {
      throw new NetworkError(error)
    }
  })
```
This works fine but i'm not sure it is the best way to achieve my goal, is there a better way to do this ?

Thanks

**Comment by elbywan** [comment]
Hi @MarlBurroW,

> For me, this example means (...)

> catch() is only for errors that are not handled by the error() or named errors handlers

The `.catch()` function in the example is the vanilla [`Promise.prototype..catch()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch) function. It is meant to catch **any** error thrown that was uncaught by other mechanisms.

> If response status code is 418, perform the attached callback, but do not fire the catch(). 

What triggers the `catch()` is the fact that you are re-throwing the error inside the callback. 
Not throwing and returning a response-like value works.

> This works fine but i'm not sure it is the best way to achieve my goal, is there a better way to do this ?

There are 2 ways of achieving this that come to my mind right now.

1) I think that a better way would be to *flag* your custom error classes and then instead of the big pattern matching case/switch/if inside just write a two line condition.

Something like (reusing your simplified example):

```js
wretch("anything")
  .errorType('json')  
  .post(somedata)
  .error(422, error => {
    // Just flag the ServerValidationError class with a field.
    // Let's say .custom = true
    throw new ServerValidationError(error)
   }
  .res(response => /* ... */)
  .catch(error => {
    if(error.custom)
      throw error
    throw HttpError(error)
   })
```

2) And a maybe even *better* way would be to do the following, removing the need to flag anything:

```js
wretch("anything")
  .errorType('json')  
  .post(somedata)
  // Instead of throwing, just return the error
  .error(422, error => new ServerValidationError(error)
  .res(response => /* ... */)
  .catch(error => { throw HttpError(error) })
  // Use .then here
  .then(result => {
    if(result instanceof Error)
        throw result
    return result
  })
```

**Comment by MarlBurroW** [comment]
Thank you very much for your answer and your explanations !

I will use your last example which sounds good to me (I didn't thought to return the error instance without throwing it). 

Thank for your work

**Comment by th3fallen** [comment]
sorry to reopen this dinosaur, but I'm trying to do something very similar except at a global level I've tried using .catcher but that doesn't appear to get me the win I want. is there any way to modify the error payload in a middleware for instance?

just like elbywan was attempting I want to throw a custom error class down to anything that uses this wretch client.

**Comment by elbywan** [comment]
Hey @th3fallen 👋 

> sorry to reopen this dinosaur

No worries! 

>  I'm trying to do something very similar except at a global level I've tried using .catcher but that doesn't appear to get me the win I want
> is there any way to modify the error payload in a middleware for instance?

Could you please post a code sample of what you are trying to achieve? 
I'm not sure I understand the use case without a concrete example.

**Comment by elbywan** [comment]
> long short is i want to be able to do something like...

Thanks for the sample 👍 

> the ultimate goal being the client could do adapter.query(asdfasd).get().catch(e => e would be one of the above error classes)

How about calling `.catch` in the resolver ?

```js
export default (baseUrl: string) => wretch(baseUrl, defaultRequestConfig())
  .errorType('json')
  .resolve(res => res.json().catch(error => { throw mutateError(e) })
  //…
```

**Comment by th3fallen** [comment]
you are a gentleman and a scholar, no idea how that didn't dawn on me but that works perfectly.
