### ISSUE TITLE
How to use your library as esm module?

### ISSUE THREAD

**Issue by viT-1** [elbywan/wretch#63]
I'm trying to use through ttsc & typescript-transform-paths
with paths in tsconfig.json
```
{
"wretch": ["https://cdn.jsdelivr.net/npm/wretch@1.5.5/dist/index.umd.js"]
}
```

but if I resolve wretch, any other related from index.umd.js are not resolved,
cause of typescript-transform-paths resolved imports only in local app code, not node_modules =(

Do you plan to publish esm version?

**Comment by elbywan** [comment]
Hi @viT-1,

`https://cdn.jsdelivr.net/npm/wretch@1.5.5/dist/index.umd.js` is only the entry point. This is the full bundle: `https://cdn.jsdelivr.net/npm/wretch@1.5.5/dist/bundle/wretch.js`

**Comment by viT-1** [comment]
I'm trying to declare path for esm loading (tsconfig paths) as
`https://cdn.jsdelivr.net/npm/wretch@1.5.5/dist/bundle/wretch.min.js`
And no success, cause it is CommonJs module, not esm =( Got error:
`The requested module 'https://cdn.jsdelivr.net/npm/wretch@1.5.5/dist/bundle/wretch.min.js' does not provide an export named 'default'`

But even I "hack" my transpiled ts to js files with `import wretch from` to `import * as wretch from` still haven't success with different error: `"TypeError: wretch is not a function"`
with ts code:
```
import wretch from 'wretch';
wretch(this.data.href)
	.get()
	.json(json => {
		console.log(json);
	});
```

**Comment by viT-1** [comment]
[My project](https://github.com/viT-1/systemjs-ts-es6-vue) for example using vue with SystemJS for production & esm for dev testing. I am using vue esm version [there](https://github.com/viT-1/systemjs-ts-es6-vue/blob/master/src/tsconfig.dev.json#L11).

**Comment by elbywan** [comment]
I'm sorry but I have a hard time understanding the issue. `wretch` is already published as an esm module.

```html
<!DOCTYPE html>
<html>
<body>
    <img id="sprite"></img>
    <script type="module">
        import wretch from 'https://unpkg.com/wretch@1.5.5/dist/index.js'

        const imageTag = document.getElementById("sprite")
        wretch('https://pokeapi.co/api/v2/pokemon/pikachu/')
            .get()
            .json(pikachu => {
                imageTag.src = pikachu.sprites.front_default
            })
    </script>
</body>
</html>
```

**Comment by viT-1** [comment]
But if I use wretch as `import wretch from 'wretch'` in typescript module I cant use such resolution,
I need esm bundle not index entry point.

**Comment by elbywan** [comment]
Ah I see, I'll add an esm bundle later today 👍.

**Comment by elbywan** [comment]
Version 1.6.0 has just been released with the esm bundle: https://unpkg.com/wretch@1.6.0/dist/bundle/wretch.esm.js

**Comment by viT-1** [comment]
When it will be [on jsdeliv](https://www.jsdelivr.com/package/npm/wretch?path=dist)r?

**Comment by elbywan** [comment]
https://cdn.jsdelivr.net/npm/wretch@1.6.0/dist/bundle/wretch.esm.js

**Comment by viT-1** [comment]
Strange, this link is working, but visually in dist folder I don't see it.

**Comment by viT-1** [comment]
I'm sleeping! _bundle_ =)))
