### ISSUE TITLE
Failed to execute 'json' on 'Response': body stream is locked in catcher

### ISSUE THREAD

**Issue by alvteren** [elbywan/wretch#64]
Hi!

I can't read the response body in catcher. I get error 

> Failed to execute 'json' on 'Response': body stream is locked

```javascript
wretch()
  .url('https://api-sdvor-stage.itlabs.io/demetra/api/v1/aerated_concrete_block_leads/')
  .content('application/json')
  .post(JSON.stringify({ productId: 1, phone: '123', cityId: 1000 }))
  .badRequest(async ({ response }) => {
    console.log(await response.json());
  })
  .res();
```

This code sample can try [here](https://svelte.dev/repl/550b9fc43e264fe7b4929396cac75c13?version=3)

How to get correctly the response body in catcher.

Thank you and sorry for my English :)

**Comment by elbywan** [comment]
Hi @alverten,

```js
.badRequest(error => {
    // error already contains the response body
    console.log(error);
    // => Error: {"phone":["Некорректный номер телефона"]}
})
```

**Comment by alvteren** [comment]
I want to receive a js object or json and after will work with it

**Comment by alvteren** [comment]
I want to get the value on the field 'phone'

**Comment by elbywan** [comment]
`JSON.parse(error.message)`?

**Comment by alvteren** [comment]
Oh, thank you so much. It is ok.
