### ISSUE TITLE
Disable Error Logs in Console

### ISSUE THREAD

**Issue by felix-voicehub** [elbywan/wretch#65]
Hey,

I'm using wretch to make `HEAD` requests in order to determine if a resource exists or not. Based on the returned status/error, I am displaying something to the user. However, I'd like wretch to not console log it's 404 in those cases. I've tried wrapping a try/catch around the call, and also using the provided callbacks, but the error gets console logged regardless.

This is what I'd like to disable to be logged:
![image](https://user-images.githubusercontent.com/49151885/71249162-d8b4b780-231c-11ea-9fe5-19a5fb40d2ad.png)

Any ideas?

```js
resourceDoesNotExist(url) {
	return api
		.url(url)
		.head()
		/* The next 3 lines are probably all the same */
		.notFound(() => true)
		.error(404, () => true)
		.res((response) => {
			if (/4\d\d/.test(response.status) === true) {
				return true;
			}

			return false;
		});
},
```

**Comment by elbywan** [comment]
Hi @felix-voicehub,

I don't think that it's related to wretch. Chrome prints when a response has an http code >= 400 by default. 

You can disable these logs by unticking the `Hide network` checkbox:

<img width="759" alt="Capture d’écran 2019-12-20 à 21 11 26" src="https://user-images.githubusercontent.com/3428394/71289430-5f918080-236d-11ea-86a4-d04759051433.png">
