### ISSUE TITLE
Body not set on delete requests

### ISSUE THREAD

**Issue by Arevico** [elbywan/wretch#67]
in the following code example, the body is not set:

`
        window.Api.url('/me/delete')
        .delete(this.deleteAccountRequest)
        .badRequest(err => this.errors = JSON.parse(err.message).errors)
        .res(type => {
          this.requestState = 'done';
          this.errors = {};
        });
`

I would be great (since delete requests may contain a body) if this is executed correctly aswel.

**Comment by elbywan** [comment]
Hi @Arevico,

> in the following code example, the body is not set:
> […]
> I would be great (since delete requests may contain a body) if this is executed correctly aswel.

I think that there is nothing in your example actually setting the body.  

You can use the `.json(…)` method (amongst others) with a payload to do that:

```js
wretch(url).json({hello: 'world'}).delete().res(…)
```
