### ISSUE TITLE
[Feature request] Configure protected routes

### ISSUE THREAD

**Issue by ssaric** [elbywan/wretch#69]
Hi, 

Currently I have setup similar to this one:

```js
const API = wretch(environment.baseApi);

export const SESSION = API.url(environment.api.session);
export const CONNECT_GOOGLE = API.url(environment.api.connectGoogle);
export const CONNECT_FACEBOOK = API.url(environment.api.connectFacebook);
export const EXPLORE = API.url(environment.api.explore);
export const ACCOUNT = API.url(environment.api.account);
export const OFFER = API.url(environment.api.offer);
```

I'd like to pass the options to the wretch something like 
```js
export const SESSION = API.url(environment.api.session).options({ protected: true});
```
And then create a middleware that checks if the route is protected, and if it is retrieve token from the Redux store in my case and add it as Authorization header.

Before you say, why not add headers immediately, I will tell you that I have problem with the order of execution. The APIs are created before store is initialized. So my store will always return undefined on initial run. Current workaround for me is to add headers when I am actually calling the API, which creates a lot of duplicated code.

What do you think?

**Comment by elbywan** [comment]
> What do you think?

Creating a middleware is one option indeed, and would solve the issue but it might a bit overkill.

One thing I would advise would be use the [.defer()](https://github.com/elbywan/wretch#defercallback-originalrequest-wretcher-url-string-options-object--wretcher-clear--false) function instead. It has been created for use cases like yours and is easier to setup.

Something like:

```js
const API = wretch(environment.baseApi).defer((api, url, options)  => {
  if(options.protected) {
    // Assuming you have a direct reference to the Redux store.
    // If not, can also be pased as a wretch option during the call.
    const token = getTokenFromRedux()
    return api.auth(token)
  }
  return api
})
```

**Comment by ssaric** [comment]
Awesome! Thank you very much. Your wrapper is a lifesaver. I might create a medium post that will feature this library. I want to write a post about how clean API frontend calls can be.

**Comment by elbywan** [comment]
That is great, thanks!
