### ISSUE TITLE
"(intermediate value)(...)(...) is not a function"

### ISSUE THREAD

**Issue by JustinLutsky** [elbywan/wretch#72]
Any idea why I'd be getting: 

"(intermediate value)(...)(...) is not a function"

calling...

            let res = await request.post(body).text();
            res = JSON.parse(res.replace(/^\ufeff/g, ''));
            return res;

Works fine testing locally with ts-node, but throwing error after deploying to AWS lambda.

**Comment by determin1st** [comment]
you dont need to remove special BOM markers and stuff there,
modern browser's api does it anyway so..

also, the post method may be detected automatically..
as far as response data be parsed to proper content-type.

**Comment by elbywan** [comment]
Hi @JustinLutsky,

> Any idea why I'd be getting:

No idea, sorry 😕. The code snippet looks ok to me.
