### ISSUE TITLE
How to handle SSL Pinning using wretch?

### ISSUE THREAD

**Issue by PragyaSingla** [elbywan/wretch#73]

**Comment by elbywan** [comment]
Hi @PragyaSingla,

This does not seem directly related to `wretch`. 

If you are developing on Android, and using react-native then you should look how to deal with that using their `fetch` version as wretch is using `fetch` under the hood.

**Comment by PragyaSingla** [comment]
If i need to add certificates, wretch will not work. Right?

**Comment by elbywan** [comment]
I don't see why it wouldn't.

As I said, it all depends on the  underlying `fetch` implementation you are using, for instance [`node-fetch`](https://github.com/node-fetch/node-fetch#custom-agent) allows it through a node.js [`Agent`](https://nodejs.org/api/https.html#https_class_https_agent).

Given the amount of detail you provided, I can only advise you to look at your platform documentation.
