### ISSUE TITLE
Is it possible to add clarifications on how to link the libary to the project?

### ISSUE THREAD

**Issue by Konstantin-Koktashev** [elbywan/wretch#77]
hey there, I'm  a fairly new developer,
found your lib and think its awesome what you did with fetch,
However, After I installed the library using npm,
i don't exactly know  what file i need to link in my HTML or where,
i did get to manage to get it to work with the the cdn provided.
could u clarify that so total newbies can also enjoy your work?

**Comment by elbywan** [comment]
Hello @Konstantin-Koktashev,

> i did get to manage to get it to work with the the cdn provided.

Glad to see that you made it work!

> However, After I installed the library using npm,
i don't exactly know what file i need to link in my HTML or where,

> could u clarify that so total newbies can also enjoy your work?

Thanks for the suggestion, but I really don't think that a tutorial on how to use `npm` and write `<script>` tags in html files would be relevant in the documentation that is already quite extensive.

There are a lot of resources available online that could help regarding these issues.
