### ISSUE TITLE
Support stream response

### ISSUE THREAD

**Issue by ChamNouki** [elbywan/wretch#93]
With fetch I can do :
```javascript
fetch('some_url', { headers: { Accept: 'application/stream+json' } })
     .then(response => response.body)
     .then(stream => new Promise(resolve => {
       stream.on('data', data => {
         console.log(new TextDecoder().decode(data));
       });

       stream.on('end', data => {
         console.log(data);
         resolve([]);
       });
     }));
```

Could be nice to be able to do the same with wretcher ! Something like :
```javascript
wretcher
    .url('some_url')
    .accept('application/stream+json')
    .get()
.stream()
.on('data', data => {
     console.log(new TextDecoder().decode(data));
})
.on('end', data => {
     console.log(new TextDecoder().decode(data));
})
```

**Comment by elbywan** [comment]
Hi @ChamNouki,

> Could be nice to be able to do the same with wretcher

This is an interesting idea!

```js
stream.on('data'…
```

Unfortunately, streams are an advanced use case and usually much more complicated than the example you posted (that has some issues in the way chunks are handled I think).

Also, the syntax you used is very specific to `node-fetch`, the standard is [completely different](https://developer.mozilla.org/en-US/docs/Web/API/Streams_API/Using_readable_streams). `wretch` should be platform agnostic.

For these reasons, I think it would be better to leave it the way it is. If you want to handle a stream in a generic way, there is the option to simply write a function:

```html
<script type="module">
  import wretch from 'https://unpkg.com/wretch/dist/index.js'

  const chunks = response => new Promise(resolve => {
    const reader = response.body.getReader()
    const chunks = []

    function pump() {
      return reader.read().then(({ done, value }) => {
        if (done) {
          return resolve(chunks)
        }
        chunks.push(value)
        return pump()
      })
    }

    return pump()
  })

  wretch('https://jsonplaceholder.typicode.com/posts/1')
    .get()
    .res(chunks)
    .then(console.log)
</script>
```

**Comment by ChamNouki** [comment]
Yeah my idea was clearly an idea to be discussed, and yes my example came from node-fetch ^_^. 

My objective working with stream is to be able to use a reactive programming library like RxJS and process result as they arrived from request instead of waiting for the response to be complete and then process an array. 

Your exemple seems to be ok but unfortunately does not work as expected on my side. The `body` property in the `response` does not contain `getReader()` methods. Thats why I fall back to fetch.

**Comment by elbywan** [comment]
> Your exemple seems to be ok but unfortunately does not work as expected on my side. The body property in the response does not contain getReader() methods. Thats why I fall back to fetch.

Yes my example was using the browsers apis.
