### ISSUE TITLE
Getting a 404 only when I use a reusable wretch object

### ISSUE THREAD

**Issue by nhill-cpi** [elbywan/wretch#94]
Hi there,

I love the library so far. I'm using wretch for my app's logout call now, and encountering an issue.

When I _do not_ use a reusable wretch object to make the call, the call succeeds. This is what that looks like:
```
wretch('logout/')
    .options({ credentials: "include", mode: "cors" })
    .get()
    .unauthorized(error => {
      window.location = utils.getLogoutUrl();
    })
    .res(response => {
      window.location = utils.getLogoutUrl();
    })
  }
```

When I _do use_ a reusable wretch object, with the same `logout/` url, the call fails because the requested URL results in a 404. This is what that looks like:

```
const apiFetch = wretch()
  .accept("application/json")
  .content("application/json")
  .options({
    credentials: "include", mode: "cors"
  })
  .catcher(401, err => window.location = utils.getLogoutUrl());

apiFetch
  .url('logout/')
  .get()
  .res(response => {
    window.location = utils.getLogoutUrl();
  })
```

What's the cause of the discrepancy? Why isn't the latter code working?

Thanks!

**Comment by elbywan** [comment]
Hey @nhill-cpi,

> What's the cause of the discrepancy?

It seems like the reusable wretch instance is configured to send the following headers.

```js
.accept("application/json")
.content("application/json")
```

But `/logout` does not seems to expect a request body or reply with a json payload. I don't have any knowledge of the server you are calling, but maybe that is the reason why you get 404s?

**Comment by nhill-cpi** [comment]
Thanks for the quick response @elbywan . That was indeed the issue - I'm not sure why that produces a 404, but thanks for pointing that out!
