### ISSUE TITLE
Delete the auth header

### ISSUE THREAD

**Issue by Azurox** [elbywan/wretch#95]
Hi,
Is there a way to delete the Auth header without recreating the entire wrecht object ?
I tried :
`api = api.auth(null);`
`api = api.auth(undefined);`
`api = api.auth();`

And the authorization is still present in every request with either `null` or `undefined` as value

Thank you 😄

**Comment by elbywan** [comment]
Hi @Azurox,

> Is there a way to delete the Auth header without recreating the entire wrecht object ?

There is no shorthand to do that, but it is possible to mutate the 'hidden' headers object.

```js
/* The imperative way: */
const w = wretch('/').auth('token')
delete w._options.headers['Authorization']
w.get().text(console.log)

/* You could also use the `.defer` function to delay mutating the header just before the request is sent in the chain. */
wretch('/')
  .auth('token')
  .defer(w => delete w._options.headers['Authorization'] && w)
  .get()
  .text(console.log)
```

**Comment by elbywan** [comment]
@Azurox closing the issue, feel free to reopen if you have other related questions

**Comment by a-eid** [comment]
@elbywan it would be nice if there was a way to completely strip a certain header from a wretch instance 

```tsx
delete w.defaults.header.Authentication
```

**Comment by elbywan** [comment]
Hey @a-eid,

> it would be nice if there was a way to completely strip a certain header from a wretch instance

Unless I'm mistaken, I think that the code snippet above that exactly that?
