### ISSUE TITLE
Bug: Mutable errorType configuration

### ISSUE THREAD

**Issue by mrazorvin** [elbywan/wretch#97]
Hello,

Following method could cause error parsing issues. You allow user to call it on specific Wretches instance, but it will mutate all existed instances, and all future instances.

```
    errorType(method: "text" | "json") {
        conf.errorType = method
        return this
    }
```

The hotfix will be to make it `static` , or complete remove it

The popper solution will be to make `config` property immutable similarly to wretcher instance

**Comment by elbywan** [comment]
Hi @mrazorvin,

I don't think that this is a bug. Quoting [the documentation](https://github.com/elbywan/wretch#errortypemethod-text--json--text):

```
Sets the method (text, json ...) used to parse the data contained in the response body in case of an HTTP error.

Persists for every subsequent requests.
```

**Comment by mrazorvin** [comment]
Well at least in (JS Docs/TS types) this sentence (without example) sound like a `every subsequent requests for current instance`

**Comment by elbywan** [comment]
SHould be fixed as pat of the v2 refactor.
