### ISSUE TITLE
Improve stack trace

### ISSUE THREAD

**Issue by mrazorvin** [elbywan/wretch#98]
The problem: Failed request's stack trace contains only single entry (this happens because error object created in async context). 
Without proper stack trace, tools like Sentry, can't correctly group errors

![Screenshot_2020-11-18_12-26-25_Updated](https://user-images.githubusercontent.com/1443614/99535192-d897be80-29a8-11eb-8af2-37aa4591d5e1.png)

Solution: Add stack trace from sync context (similarly thing what zone.js is doing)

```
...
+    var originError = new Error('wretcher sync error stack');
     var throwingPromise = fetchRequest
         .catch(function (error) {
         throw new WretchErrorWrapper(error);
@@ -39,6 +40,7 @@ export var resolver = function (wretcher) {
             return response[conf.errorType || "text"]().then(function (msg) {
                 // Enhances the error object
+                err.stack = err.stack + "\n" + [...originError.stack.split("\n").slice(2)].join("\n");
                 ...

```

**Comment by elbywan** [comment]
Hi @mrazorvin,

> The problem: Failed request's stack trace contains only single entry (this happens because error object created in async context).

I understand the issue, having a proper stack trace is indeed important when using tools like Sentry.

>  `err.stack = err.stack + "\n" + [...originError.stack.split("\n").slice(2)].join("\n");`

Unfortunately the solution you propose has several issues all coming from the fact that `Error.prototype.stack` is a [non-standard](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Stack) feature:

- The `.stack` format is widely different from browser to browser. I only tried with Firefox and Chrome but the difference is significant.
- While I was looking at the angular `zone.js` code [I noticed a comment](https://github.com/angular/angular/blob/master/packages/zone.js/lib/common/error-rewrite.ts#L135) warning that some browsers do not event seem to support stack mutation.
- Stack frame also seems different. Firefox puts non-async frames, not Chrome.

For all these reasons, it does not seem reasonable to use the exact code you posted.

I also do not use Sentry myself and therefore cannot experiment much on the subject, but if you can come up with a different approach it would be great.

**Comment by mrazorvin** [comment]
````
const stack = console.trace();
....
class WretcherError extends Error {
 constructor(message) {
   this.message = message;
   this.stack = stack;
   status = ..
   response = ..
 }
}
....
new WrecherError(error.message)
```

**Comment by elbywan** [comment]
SHould be fixed as pat of the v2 refactor.
